openapi: 3.2.0
info:
  title: Svix Webhooks AutoConfig API
  description: 'Welcome to the Svix API documentation!


    Useful links: [Homepage](https://www.svix.com) | [Support email](mailto:support+docs@svix.com) | [Blog](https://www.svix.com/blog/) | [Slack Community](https://www.svix.com/slack/)


    # Introduction


    This is the reference documentation and schemas for the [Svix webhook service](https://www.svix.com) API. For tutorials and other documentation please refer to [the documentation](https://docs.svix.com).


    ## Main concepts


    In Svix you have four important entities you will be interacting with:


    - `messages`: these are the webhooks being sent. They can have contents and a few other properties.

    - `application`: this is where `messages` are sent to. Usually you want to create one application for each user on your platform.

    - `endpoint`: endpoints are the URLs messages will be sent to. Each application can have multiple `endpoints` and each message sent to that application will be sent to all of them (unless they are not subscribed to the sent event type).

    - `event-type`: event types are identifiers denoting the type of the message being sent. Event types are primarily used to decide which events are sent to which endpoint.



    ## Authentication


    Get your authentication token (`AUTH_TOKEN`) from the [Svix dashboard](https://dashboard.svix.com) and use it as part of the `Authorization` header as such: `Authorization: Bearer ${AUTH_TOKEN}`. For more information on authentication, please refer to the [authentication token docs](https://docs.svix.com/api-keys).


    <SecurityDefinitions />



    ## Code samples


    The code samples assume you already have the respective libraries installed and you know how to use them. For the latest information on how to do that, please refer to [the documentation](https://docs.svix.com/).



    ## Idempotency


    Svix supports [idempotency](https://en.wikipedia.org/wiki/Idempotence) for safely retrying requests without accidentally performing the same operation twice. This is useful when an API call is disrupted in transit and you do not receive a response.


    To perform an idempotent request, pass the idempotency key in the `Idempotency-Key` header to the request. The idempotency key should be a unique value generated by the client. You can create the key in however way you like, though we suggest using UUID v4, or any other string with enough entropy to avoid collisions. Your idempotency key should not begin with the string `auto_`, which is reserved for internal use by the client libraries.


    Svix''s idempotency works by saving the resulting status code and body of the first request made for any given idempotency key for any successful request. Subsequent requests with the same key return the same result for a period of up to 12 hours.


    Please note that idempotency is only supported for `POST` requests.



    ## Cross-Origin Resource Sharing


    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    '
  version: 1.922.0
  x-logo:
    url: https://www.svix.com/static/img/brand-padded.svg
    altText: Svix Logo
servers:
- url: https://api.eu.svix.com
  description: The Svix EU region
- url: https://api.us.svix.com
  description: The Svix US region
- url: https://api.ca.svix.com
  description: The Svix Canada region
- url: https://api.au.svix.com
  description: The Svix Australia region
- url: https://api.in.svix.com
  description: The Svix India region
tags:
- name: Webhooks AutoConfig
paths:
  /api/v1/app/{app_id}/auto-config:
    post:
      tags:
      - Webhooks AutoConfig
      summary: Create Subscription
      description: Create a new auto-config flow (creates an endpoint awaiting configuration).
      operationId: v1.endpoint.auto-config.create
      parameters:
      - in: path
        name: app_id
        description: The Application's ID or UID.
        required: true
        schema:
          description: The Application's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoConfigOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
  /api/v1/app/{app_id}/endpoint/{endpoint_id}/auto-config:
    get:
      tags:
      - Webhooks AutoConfig
      summary: Get Subscription
      description: Get the current auto-config token in censored form.
      operationId: v1.endpoint.auto-config.get
      parameters:
      - in: path
        name: app_id
        description: The Application's ID or UID.
        required: true
        schema:
          description: The Application's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      - in: path
        name: endpoint_id
        description: The Endpoint's ID or UID.
        required: true
        schema:
          description: The Endpoint's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoConfigCensoredOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
    put:
      tags:
      - Webhooks AutoConfig
      summary: Update Subscription
      description: Update an auto-config endpoint by providing endpoint details.
      operationId: v1.endpoint.auto-config.update
      parameters:
      - in: path
        name: app_id
        description: The Application's ID or UID.
        required: true
        schema:
          description: The Application's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      - in: path
        name: endpoint_id
        description: The Endpoint's ID or UID.
        required: true
        schema:
          description: The Endpoint's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscribeIn'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
  /api/v1/app/{app_id}/endpoint/{endpoint_id}/auto-config/rotate:
    post:
      tags:
      - Webhooks AutoConfig
      summary: Rotate Subscription
      description: Rotate the auth token for an auto-config endpoint.
      operationId: v1.endpoint.auto-config.rotate
      parameters:
      - in: path
        name: app_id
        description: The Application's ID or UID.
        required: true
        schema:
          description: The Application's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      - in: path
        name: endpoint_id
        description: The Endpoint's ID or UID.
        required: true
        schema:
          description: The Endpoint's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RotateSubscriptionIn'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoConfigOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
components:
  schemas:
    SinkInCommon:
      type: object
      properties:
        description:
          type: string
          default: ''
          example: An example endpoint name
        rateLimit:
          description: Deprecated, use `throttleRate` instead.
          type: integer
          format: uint16
          deprecated: true
          minimum: 1
          nullable: true
        throttleRate:
          description: 'Maximum messages per second to send to this endpoint.


            Outgoing messages will be throttled to this rate.'
          type: integer
          format: uint16
          minimum: 1
          nullable: true
        uid:
          description: Optional unique identifier for the sink.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
          nullable: true
        secret:
          description: 'The endpoint''s verification secret.


            Format: `base64` encoded random bytes optionally prefixed with `whsec_`.

            It is recommended to not set this and let the server generate the secret.'
          type: string
          pattern: ^(whsec_|whsk_|whsk1_|whpk_|whpk1_)?[a-zA-Z0-9+/=]{32,100}$
          example: whsec_C2FVsBQIhrscChlQIMV+b5sSYspob7oD
          nullable: true
        disabled:
          type: boolean
          default: false
          example: false
        filterTypes:
          type: array
          nullable: true
          items:
            description: The event type's name
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
            example: user.signup
          minItems: 1
          uniqueItems: true
          example:
          - user.signup
          - user.deleted
        channels:
          description: List of message channels this sink listens to (omit for all).
          type: array
          nullable: true
          items:
            type: string
            maxLength: 128
            pattern: ^[a-zA-Z0-9\-_.:+]+$
            example: project_1337
          maxItems: 10
          minItems: 1
          uniqueItems: true
          example:
          - project_123
          - group_2
        metadata:
          type: object
          default: {}
          additionalProperties:
            type: string
    SubscribeIn:
      type: object
      properties:
        endpoint:
          $ref: '#/components/schemas/EndpointIn'
          nullable: true
        sink:
          $ref: '#/components/schemas/AutoConfigSinkType'
          nullable: true
    HttpErrorOut:
      title: HttpError
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
      required:
      - code
      - detail
    EndpointIn:
      type: object
      properties:
        url:
          type: string
          format: uri
          minLength: 1
          maxLength: 65536
          example: https://example.com/webhook/
        description:
          type: string
          default: ''
          example: An example endpoint name
        rateLimit:
          description: Deprecated, use `throttleRate` instead.
          type: integer
          format: uint16
          deprecated: true
          minimum: 1
          nullable: true
        throttleRate:
          description: 'Maximum messages per second to send to this endpoint.


            Outgoing messages will be throttled to this rate.'
          type: integer
          format: uint16
          minimum: 1
          nullable: true
        uid:
          description: Optional unique identifier for the endpoint.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
          nullable: true
        version:
          type: integer
          format: uint16
          default: 1
          deprecated: true
          nullable: true
          minimum: 1
          example: 1
        disabled:
          type: boolean
          default: false
          example: false
        filterTypes:
          type: array
          nullable: true
          items:
            description: The event type's name
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
            example: user.signup
          minItems: 1
          uniqueItems: true
          example:
          - user.signup
          - user.deleted
        channels:
          description: List of message channels this endpoint listens to (omit for all).
          type: array
          nullable: true
          items:
            type: string
            maxLength: 128
            pattern: ^[a-zA-Z0-9\-_.:+]+$
            example: project_1337
          maxItems: 10
          minItems: 1
          uniqueItems: true
          example:
          - project_123
          - group_2
        secret:
          description: 'The endpoint''s verification secret.


            Format: `base64` encoded random bytes optionally prefixed with `whsec_`.

            It is recommended to not set this and let the server generate the secret.'
          type: string
          pattern: ^(whsec_|whsk_|whsk1_|whpk_|whpk1_)?[a-zA-Z0-9+/=]{32,100}$
          example: whsec_C2FVsBQIhrscChlQIMV+b5sSYspob7oD
          nullable: true
        metadata:
          type: object
          default: {}
          additionalProperties:
            type: string
        headers:
          type: object
          nullable: true
          additionalProperties:
            type: string
          example:
            X-Example: '123'
            X-Foobar: Bar
      required:
      - url
    RotateSubscriptionIn:
      type: object
      properties:
        signingSecret:
          default: null
          $ref: '#/components/schemas/EndpointSecretRotateIn'
          nullable: true
    EndpointSecretRotateIn:
      type: object
      properties:
        key:
          description: 'The endpoint''s verification secret.


            Format: `base64` encoded random bytes optionally prefixed with `whsec_`.

            It is recommended to not set this and let the server generate the secret.'
          type: string
          default: null
          pattern: ^(whsec_|whsk_|whsk1_|whpk_|whpk1_)?[a-zA-Z0-9+/=]{32,100}$
          example: whsec_C2FVsBQIhrscChlQIMV+b5sSYspob7oD
          nullable: true
        gracePeriodSeconds:
          description: 'How long the old secret will be valid for, in seconds.


            Valid values are between 0 (immediate expiry) and 7 days. The default is 24 hours.'
          type: integer
          format: uint32
          default: 86400
          maximum: 604800
          minimum: 0
          nullable: true
    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
      required:
      - detail
    ValidationError:
      description: Validation errors have their own schema to provide context for invalid requests eg. mismatched types and out of bounds values. There may be any number of these per 422 UNPROCESSABLE ENTITY error.
      type: object
      properties:
        loc:
          description: The location as a [`Vec`] of [`String`]s -- often in the form `["body", "field_name"]`, `["query", "field_name"]`, etc. They may, however, be arbitrarily deep.
          type: array
          items:
            type: string
        msg:
          description: The message accompanying the validation error item.
          type: string
        type:
          description: The type of error, often "type_error" or "value_error", but sometimes with more context like as "value_error.number.not_ge"
          type: string
      required:
      - loc
      - msg
      - type
    AutoConfigSinkType:
      oneOf:
      - type: object
        properties:
          type:
            type: string
            enum:
            - poller
          config:
            $ref: '#/components/schemas/SinkInCommon'
        required:
        - config
        - type
      - type: object
        properties:
          type:
            type: string
            enum:
            - http
          config:
            $ref: '#/components/schemas/EndpointIn'
        required:
        - config
        - type
    AutoConfigCensoredOut:
      type: object
      properties:
        updatedAt:
          type: string
          format: date-time
        tokenCensored:
          type: string
        endpId:
          description: The Endpoint's ID.
          type: string
          maxLength: 30
          minLength: 30
          pattern: ^ep_[A-Za-z0-9]{27}$
          example: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
      required:
      - endpId
      - tokenCensored
      - updatedAt
    AutoConfigOut:
      type: object
      properties:
        updatedAt:
          type: string
          format: date-time
        token:
          type: string
        endpId:
          description: The Endpoint's ID.
          type: string
          maxLength: 30
          minLength: 30
          pattern: ^ep_[A-Za-z0-9]{27}$
          example: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
      required:
      - endpId
      - token
      - updatedAt
    EndpointOut:
      type: object
      properties:
        id:
          description: The Endpoint's ID.
          type: string
          maxLength: 30
          minLength: 30
          pattern: ^ep_[A-Za-z0-9]{27}$
          example: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
        metadata:
          type: object
          additionalProperties:
            type: string
        url:
          type: string
          format: uri
          minLength: 1
          maxLength: 65536
          example: https://example.com/webhook/
        description:
          type: string
        rateLimit:
          description: Deprecated, use `throttleRate` instead.
          type: integer
          format: uint16
          deprecated: true
          minimum: 0
          nullable: true
        throttleRate:
          description: 'Maximum messages per second to send to this endpoint.


            Outgoing messages will be throttled to this rate.'
          type: integer
          format: uint16
          minimum: 0
          nullable: true
        uid:
          description: Optional unique identifier for the endpoint.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
          nullable: true
        version:
          type: integer
          format: int32
          deprecated: true
          minimum: 1
          example: 1
        disabled:
          type: boolean
          default: false
          example: false
        filterTypes:
          type: array
          nullable: true
          items:
            description: The event type's name
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
            example: user.signup
          minItems: 1
          uniqueItems: true
          example:
          - user.signup
          - user.deleted
        channels:
          description: List of message channels this endpoint listens to (omit for all).
          type: array
          nullable: true
          items:
            type: string
            maxLength: 128
            pattern: ^[a-zA-Z0-9\-_.:+]+$
            example: project_1337
          maxItems: 10
          minItems: 1
          uniqueItems: true
          example:
          - project_123
          - group_2
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
      - createdAt
      - description
      - id
      - metadata
      - updatedAt
      - url
      - version
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
      description: HTTP Bearer token passed in the `Authorization` header
x-tagGroups:
- name: General
  tags:
  - Background Task
  - Environment
- name: Dispatch
  tags:
  - Application
  - Event Type
  - Authentication
  - Endpoint
  - Message
  - Message Attempt
  - Integration
  - Connector
- name: Stream
  tags:
  - Stream
  - Sink
  - Event
  - Stream Event Type
  - Stream Authentication
- name: Ingest
  tags:
  - Ingest Source
  - Ingest Endpoint
- name: Operational Webhooks
  tags:
  - Webhook
  - Webhook Endpoint
- name: Statistics
  tags:
  - Statistics
- name: Utility
  tags:
  - Health
x-webhooks:
  endpoint.created:
    post:
      tags:
      - Webhook
      summary: endpoint.created
      description: Sent when an endpoint is created.
      operationId: endpoint.created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointCreatedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.created
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.deleted:
    post:
      tags:
      - Webhook
      summary: endpoint.deleted
      description: Sent when an endpoint is deleted.
      operationId: endpoint.deleted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointDeletedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.deleted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.disabled:
    post:
      tags:
      - Webhook
      summary: endpoint.disabled
      description: Sent when an endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: endpoint.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointDisabledEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: endpoint.disabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.enabled:
    post:
      tags:
      - Webhook
      summary: endpoint.enabled
      description: Sent when an endpoint has been enabled.
      operationId: endpoint.enabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointEnabledEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.enabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.updated:
    post:
      tags:
      - Webhook
      summary: endpoint.updated
      description: Sent when an endpoint is updated.
      operationId: endpoint.updated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointUpdatedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.updated
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.exhausted:
    post:
      tags:
      - Webhook
      summary: message.attempt.exhausted
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: message.attempt.exhausted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptExhaustedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.exhausted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.failing:
    post:
      tags:
      - Webhook
      summary: message.attempt.failing
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `message.attempt.exhausted` which is sent after the last failure.'
      operationId: message.attempt.failing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptFailingEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.failing
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.recovered:
    post:
      tags:
      - Webhook
      summary: message.attempt.recovered
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: message.attempt.recovered
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptRecoveredEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.recovered
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  background_task.finished:
    post:
      tags:
      - Webhook
      summary: background_task.finished
      description: Sent when a background task is finished.
      operationId: background_task.finished
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackgroundTaskFinishedEvent'
            example:
              data:
                taskId: qtask_1srOrx2ZWZBpBUvZwXKQmoEYga2
                task: application.stats
                status: finished
                data:
                  appStats:
                  - messageDestinations: 343
                    appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                    appUid: null
              type: background_task.finished
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.endpoint.disabled:
    post:
      tags:
      - Webhook
      summary: ingest.endpoint.disabled
      description: Sent when an ingest endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: ingest.endpoint.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestEndpointDisabledEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: ingest.endpoint.disabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.exhausted:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.exhausted
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: ingest.message.attempt.exhausted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptExhaustedEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.exhausted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.failing:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.failing
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `ingest.message.attempt.exhausted` which is sent after the last failure.'
      operationId: ingest.message.attempt.failing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptFailingEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.failing
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.recovered:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.recovered
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: ingest.message.attempt.recovered
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptRecoveredEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.recovered
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  message.attempt.log:
    post:
      tags:
      - Webhook
      summary: message.attempt.log
      description: Sent after message attempts are made. Contains metadata about message attempts and their results. In order to reduce the frequency of webhooks, these are sent in batches periodically.
      operationId: message.attempt.log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptLogEvent'
            example:
              data:
              - orgId: env_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                msgCreated: '2022-11-06T15:04:05Z'
                attemptStart: '2022-11-06T15:04:06Z'
                attemptEnd: '2022-11-06T15:04:07Z'
                attemptId: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                responseStatusCode: 200
                attemptCount: 1
                status: 0
                eventType: user.signup
              type: message.attempt.log
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
      x-svix-feature-flags:
      - attempt_log
      x-internal: true
