openapi: 3.2.0
info:
  title: Svix Environment API
  description: 'Welcome to the Svix API documentation!


    Useful links: [Homepage](https://www.svix.com) | [Support email](mailto:support+docs@svix.com) | [Blog](https://www.svix.com/blog/) | [Slack Community](https://www.svix.com/slack/)


    # Introduction


    This is the reference documentation and schemas for the [Svix webhook service](https://www.svix.com) API. For tutorials and other documentation please refer to [the documentation](https://docs.svix.com).


    ## Main concepts


    In Svix you have four important entities you will be interacting with:


    - `messages`: these are the webhooks being sent. They can have contents and a few other properties.

    - `application`: this is where `messages` are sent to. Usually you want to create one application for each user on your platform.

    - `endpoint`: endpoints are the URLs messages will be sent to. Each application can have multiple `endpoints` and each message sent to that application will be sent to all of them (unless they are not subscribed to the sent event type).

    - `event-type`: event types are identifiers denoting the type of the message being sent. Event types are primarily used to decide which events are sent to which endpoint.



    ## Authentication


    Get your authentication token (`AUTH_TOKEN`) from the [Svix dashboard](https://dashboard.svix.com) and use it as part of the `Authorization` header as such: `Authorization: Bearer ${AUTH_TOKEN}`. For more information on authentication, please refer to the [authentication token docs](https://docs.svix.com/api-keys).


    <SecurityDefinitions />



    ## Code samples


    The code samples assume you already have the respective libraries installed and you know how to use them. For the latest information on how to do that, please refer to [the documentation](https://docs.svix.com/).



    ## Idempotency


    Svix supports [idempotency](https://en.wikipedia.org/wiki/Idempotence) for safely retrying requests without accidentally performing the same operation twice. This is useful when an API call is disrupted in transit and you do not receive a response.


    To perform an idempotent request, pass the idempotency key in the `Idempotency-Key` header to the request. The idempotency key should be a unique value generated by the client. You can create the key in however way you like, though we suggest using UUID v4, or any other string with enough entropy to avoid collisions. Your idempotency key should not begin with the string `auto_`, which is reserved for internal use by the client libraries.


    Svix''s idempotency works by saving the resulting status code and body of the first request made for any given idempotency key for any successful request. Subsequent requests with the same key return the same result for a period of up to 12 hours.


    Please note that idempotency is only supported for `POST` requests.



    ## Cross-Origin Resource Sharing


    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    '
  version: 1.922.0
  x-logo:
    url: https://www.svix.com/static/img/brand-padded.svg
    altText: Svix Logo
servers:
- url: https://api.eu.svix.com
  description: The Svix EU region
- url: https://api.us.svix.com
  description: The Svix US region
- url: https://api.ca.svix.com
  description: The Svix Canada region
- url: https://api.au.svix.com
  description: The Svix Australia region
- url: https://api.in.svix.com
  description: The Svix India region
tags:
- name: Environment
  description: Manage your environments like development, staging and production.
paths:
  /api/v1/management/environment:
    get:
      tags:
      - Environment
      summary: List Environments
      description: List all environments.
      operationId: v1.management.environment.list
      parameters:
      - in: query
        name: limit
        description: Limit the number of returned items
        schema:
          description: Limit the number of returned items
          type: integer
          format: uint64
          maximum: 250
          minimum: 1.0
        style: form
      - in: query
        name: iterator
        description: The iterator returned from a prior invocation
        schema:
          description: The iterator returned from a prior invocation
          type: string
          maxLength: 31
          minLength: 31
          pattern: ^org_[A-Za-z0-9]{27}$
          nullable: true
          example: org_1srOrx2ZWZBpBUvZwXKQmoEYga2
        style: form
      - in: query
        name: order
        description: The sorting order of the returned items
        schema:
          description: The sorting order of the returned items
          $ref: '#/components/schemas/Ordering'
          nullable: true
        style: form
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse_EnvironmentModelOut_'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
    post:
      tags:
      - Environment
      summary: Create Environment
      description: Create a new environment.
      operationId: v1.management.environment.create
      parameters:
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentModelIn'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentModelOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
  /api/v1/management/environment/{env_id}:
    get:
      tags:
      - Environment
      summary: Get Environment
      description: Get an environment.
      operationId: v1.management.environment.get
      parameters:
      - in: path
        name: env_id
        description: The Environment's ID.
        required: true
        schema:
          description: The Environment's ID.
          type: string
          maxLength: 31
          minLength: 31
          pattern: ^org_[A-Za-z0-9]{27}$
          example: org_1srOrx2ZWZBpBUvZwXKQmoEYga2
        style: simple
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentModelOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
    put:
      tags:
      - Environment
      summary: Update Environment
      description: Update an environment.
      operationId: v1.management.environment.update
      parameters:
      - in: path
        name: env_id
        description: The Environment's ID.
        required: true
        schema:
          description: The Environment's ID.
          type: string
          maxLength: 31
          minLength: 31
          pattern: ^org_[A-Za-z0-9]{27}$
          example: org_1srOrx2ZWZBpBUvZwXKQmoEYga2
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentModelUpdate'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentModelOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
    delete:
      tags:
      - Environment
      summary: Delete Environment
      description: Delete an environment.
      operationId: v1.management.environment.delete
      parameters:
      - in: path
        name: env_id
        description: The Environment's ID.
        required: true
        schema:
          description: The Environment's ID.
          type: string
          maxLength: 31
          minLength: 31
          pattern: ^org_[A-Za-z0-9]{27}$
          example: org_1srOrx2ZWZBpBUvZwXKQmoEYga2
        style: simple
      responses:
        '204':
          description: no content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
  /api/v1/environment/export:
    post:
      tags:
      - Environment
      summary: Export Environment Configuration
      description: 'Download a JSON file containing all org-settings and event types.


        Note that the schema for [`EnvironmentOut`] is subject to change. The fields

        herein are provided for convenience but should be treated as JSON blobs.'
      operationId: v1.environment.export
      parameters:
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-codeSamples:
      - lang: TypeScript
        label: JavaScript
        source: const response = await svix.environment.export();
      - lang: TypeScript
        label: TypeScript
        source: const response = await svix.environment.export();
      - lang: Python
        label: Python
        source: response = svix.environment.export()
      - lang: Python
        label: Python (Async)
        source: response = await svix.environment.export()
      - lang: Go
        label: Go
        source: response, err := svix.Environment.Export(ctx, nil)
      - lang: Kotlin
        label: Kotlin
        source: val response = svix.environment.export()
      - lang: Java
        label: Java
        source: var response = svix.getEnvironment().export();
      - lang: Ruby
        label: Ruby
        source: response = svix.environment.export
      - lang: Rust
        label: Rust
        source: let response = svix.environment().export(None).await?;
      - lang: C#
        label: C#
        source: var response = svix.Environment.Export();
      - lang: PHP
        label: PHP
        source: $response = $svix->environment->export();
      - lang: Shell
        label: CLI
        source: svix environment export
      - lang: Shell
        label: cURL
        source: "curl -X 'POST' \\\n  'https://api.eu.svix.com/api/v1/environment/export' \\\n  -H 'Authorization: Bearer AUTH_TOKEN' \\\n  -H 'Accept: application/json'"
  /api/v1/environment/import:
    post:
      tags:
      - Environment
      summary: Import Environment Configuration
      description: 'Import a configuration into the active organization.


        It doesn''t delete anything, only adds / updates what was passed to it.


        Note that the schema for [`EnvironmentIn`] is subject to change. The fields

        herein are provided for convenience but should be treated as JSON blobs.'
      operationId: v1.environment.import
      parameters:
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentIn'
        required: true
      responses:
        '204':
          description: no content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-codeSamples:
      - lang: TypeScript
        label: JavaScript
        source: "await svix.environment.import({\n  eventTypes: [],\n  settings: {},\n  connectors: [],\n});"
      - lang: TypeScript
        label: TypeScript
        source: "await svix.environment.import({\n  eventTypes: [],\n  settings: {},\n  connectors: [],\n});"
      - lang: Python
        label: Python
        source: "svix.environment.import_(\n    EnvironmentIn(\n        event_types=[],\n        settings={},\n        connectors=[],\n    ),\n)"
      - lang: Python
        label: Python (Async)
        source: "await svix.environment.import_(\n    EnvironmentIn(\n        event_types=[],\n        settings={},\n        connectors=[],\n    ),\n)"
      - lang: Go
        label: Go
        source: "err := svix.Environment.Import(\n\tctx,\n\tEnvironmentIn{EventTypes: []EventTypeIn{}, Settings: nil, Connectors: []ConnectorIn{}},\n\tnil,\n)"
      - lang: Kotlin
        label: Kotlin
        source: "svix.environment.import(\n    EnvironmentIn(eventTypes = listOf(), settings = mapOf(), connectors = listOf())\n)"
      - lang: Java
        label: Java
        source: "svix.getEnvironment()\n        .import_(\n            new EnvironmentIn().eventTypes(List.of()).settings(Map.of()).connectors(List.of()));"
      - lang: Ruby
        label: Ruby
        source: 'response = svix.environment.import({eventTypes: [], settings: {}, connectors: []})'
      - lang: Rust
        label: Rust
        source: "svix.environment()\n    .import(\n        EnvironmentIn {\n            event_types: Some(vec![]),\n            settings: Some(serde_json::json!({})),\n            connectors: Some(vec![]),\n        },\n        None,\n    )\n    .await?;"
      - lang: C#
        label: C#
        source: "var response = svix.Environment.Import(\n    new EnvironmentIn\n    {\n        EventTypes = [],\n        Settings = new Dictionary<string, string> { },\n        Connectors = [],\n    }\n);"
      - lang: PHP
        label: PHP
        source: "$svix->environment->import(\n    EnvironmentIn::create()\n    ->withEventTypes([])\n    ->withConnectors([])\n);"
      - lang: Shell
        label: CLI
        source: "svix environment import '{\n    \"eventTypes\": [],\n    \"settings\": {},\n    \"connectors\": []\n  }'"
      - lang: Shell
        label: cURL
        source: "curl -X 'POST' \\\n  'https://api.eu.svix.com/api/v1/environment/import' \\\n  -H 'Authorization: Bearer AUTH_TOKEN' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"eventTypes\": [],\n    \"settings\": {},\n    \"connectors\": []\n  }'"
components:
  schemas:
    EnvironmentOut:
      type: object
      properties:
        version:
          type: integer
          format: int
          default: 1
        createdAt:
          type: string
          format: date-time
        eventTypes:
          type: array
          items:
            $ref: '#/components/schemas/EventTypeOut'
        settings:
          type: object
          additionalProperties: true
          nullable: true
        connectors:
          type: array
          items:
            $ref: '#/components/schemas/ConnectorOut'
      required:
      - connectors
      - createdAt
      - eventTypes
      - settings
    EnvironmentIn:
      type: object
      properties:
        eventTypes:
          type: array
          items:
            $ref: '#/components/schemas/EventTypeIn'
          nullable: true
        settings:
          type: object
          additionalProperties: true
          nullable: true
        connectors:
          type: array
          items:
            $ref: '#/components/schemas/ConnectorIn'
          nullable: true
    ConnectorKind:
      type: string
      enum:
      - Custom
      - AgenticCommerceProtocol
      - CloseCRM
      - CustomerIO
      - Discord
      - Hubspot
      - Inngest
      - Loops
      - Otel
      - Resend
      - Salesforce
      - Segment
      - Sendgrid
      - Slack
      - Teams
      - TriggerDev
      - Windmill
      - Zapier
    HttpErrorOut:
      title: HttpError
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
      required:
      - code
      - detail
    EnvironmentRegion:
      type: string
      enum:
      - eu
      - us
      - au
      - ca
      - self-hosted
    EnvironmentModelIn:
      type: object
      properties:
        name:
          description: Environment name for human consumption.
          type: string
          minLength: 1
          maxLength: 255
          example: My environment
        type:
          $ref: '#/components/schemas/EnvironmentType'
          example: development
      required:
      - name
      - type
    EventTypeIn:
      type: object
      properties:
        name:
          description: The event type's name
          type: string
          maxLength: 256
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: user.signup
        description:
          type: string
          example: A user has signed up
        archived:
          type: boolean
          default: false
          example: false
        deprecated:
          type: boolean
          default: false
        schemas:
          description: The schema for the event type for a specific version as a JSON schema.
          type: object
          nullable: true
          additionalProperties: true
          example:
            '1':
              title: Invoice Paid Event
              description: An invoice was paid by a user
              type: object
              properties:
                invoiceId:
                  description: The invoice id
                  type: string
                userId:
                  description: The user id
                  type: string
              required:
              - invoiceId
              - userId
        groupName:
          description: The event type group's name
          type: string
          maxLength: 256
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: user
          nullable: true
        featureFlags:
          type: array
          default: null
          nullable: true
          items:
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
          minItems: 1
          uniqueItems: true
          example:
          - cool-new-feature
        featureFlag:
          description: Deprecated, use `featureFlags` instead.
          type: string
          default: null
          deprecated: true
          maxLength: 256
          pattern: ^[a-zA-Z0-9\-_.]+$
          nullable: true
      required:
      - description
      - name
    ConnectorIn:
      type: object
      properties:
        name:
          type: string
          example: My first connector
        uid:
          description: The Connector's UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
          nullable: true
        logo:
          type: string
          format: uri
          nullable: true
          example: https://example.com/logo.png
        description:
          type: string
          default: ''
          example: Example connector description
        kind:
          default: Custom
          $ref: '#/components/schemas/ConnectorKind'
          example: Slack
        instructions:
          type: string
          default: ''
          example: Markdown-formatted instructions
        allowedEventTypes:
          type: array
          nullable: true
          items:
            description: The event type's name
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
            example: user.signup
          minItems: 1
          uniqueItems: true
          example:
          - user.signup
          - user.deleted
        transformation:
          type: string
          minLength: 10
          maxLength: 51200
          example: function handler(webhook) { /* ... */ }
        featureFlags:
          type: array
          default: null
          items:
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
          uniqueItems: true
          nullable: true
        productType:
          default: null
          $ref: '#/components/schemas/ConnectorProduct'
          nullable: true
      required:
      - name
      - transformation
    EnvironmentModelUpdate:
      type: object
      properties:
        name:
          description: Environment name for human consumption.
          type: string
          minLength: 1
          maxLength: 255
          example: My environment
      required:
      - name
    ConnectorOut:
      type: object
      properties:
        id:
          description: The Connector's ID.
          type: string
          maxLength: 34
          minLength: 34
          pattern: ^trtmpl_[A-Za-z0-9]{27}$
          example: trtmpl_1srOrx2ZWZBpBUvZwXKQmoEYga2
        orgId:
          description: The Environment's ID.
          type: string
          maxLength: 31
          minLength: 31
          pattern: ^org_[A-Za-z0-9]{27}$
          example: org_1srOrx2ZWZBpBUvZwXKQmoEYga2
        uid:
          description: The Connector's UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
          nullable: true
        kind:
          $ref: '#/components/schemas/ConnectorKind'
        name:
          type: string
        logo:
          type: string
          format: uri
          nullable: true
        description:
          type: string
        instructions:
          type: string
        allowedEventTypes:
          type: array
          nullable: true
          items:
            description: The event type's name
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
            example: user.signup
          minItems: 1
          uniqueItems: true
          example:
          - user.signup
          - user.deleted
        transformation:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        transformationUpdatedAt:
          type: string
          format: date-time
        featureFlags:
          type: array
          default: null
          nullable: true
          items:
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
          uniqueItems: true
          example:
          - cool-new-feature
        productType:
          $ref: '#/components/schemas/ConnectorProduct'
      required:
      - createdAt
      - description
      - id
      - instructions
      - kind
      - name
      - orgId
      - productType
      - transformation
      - transformationUpdatedAt
      - updatedAt
    ConnectorProduct:
      type: string
      enum:
      - Dispatch
      - Stream
    EventTypeOut:
      type: object
      properties:
        name:
          description: The event type's name
          type: string
          maxLength: 256
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: user.signup
        description:
          type: string
          example: A user has signed up
        archived:
          type: boolean
          default: false
          example: false
        deprecated:
          type: boolean
        schemas:
          description: The schema for the event type for a specific version as a JSON schema.
          type: object
          nullable: true
          additionalProperties: true
          example:
            '1':
              title: Invoice Paid Event
              description: An invoice was paid by a user
              type: object
              properties:
                invoiceId:
                  description: The invoice id
                  type: string
                userId:
                  description: The user id
                  type: string
              required:
              - invoiceId
              - userId
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        groupName:
          description: The event type group's name
          type: string
          maxLength: 256
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: user
          nullable: true
        featureFlags:
          type: array
          nullable: true
          items:
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
          uniqueItems: true
          example:
          - cool-new-feature
        featureFlag:
          type: string
          maxLength: 256
          pattern: ^[a-zA-Z0-9\-_.]+$
          nullable: true
      required:
      - createdAt
      - deprecated
      - description
      - name
      - updatedAt
    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
      required:
      - detail
    ValidationError:
      description: Validation errors have their own schema to provide context for invalid requests eg. mismatched types and out of bounds values. There may be any number of these per 422 UNPROCESSABLE ENTITY error.
      type: object
      properties:
        loc:
          description: The location as a [`Vec`] of [`String`]s -- often in the form `["body", "field_name"]`, `["query", "field_name"]`, etc. They may, however, be arbitrarily deep.
          type: array
          items:
            type: string
        msg:
          description: The message accompanying the validation error item.
          type: string
        type:
          description: The type of error, often "type_error" or "value_error", but sometimes with more context like as "value_error.number.not_ge"
          type: string
      required:
      - loc
      - msg
      - type
    EnvironmentType:
      type: string
      enum:
      - development
      - production
    EnvironmentModelOut:
      type: object
      properties:
        id:
          description: The Environment's ID.
          type: string
          maxLength: 31
          minLength: 31
          pattern: ^org_[A-Za-z0-9]{27}$
          example: org_1srOrx2ZWZBpBUvZwXKQmoEYga2
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        region:
          $ref: '#/components/schemas/EnvironmentRegion'
        name:
          type: string
        type:
          $ref: '#/components/schemas/EnvironmentType'
      required:
      - createdAt
      - id
      - name
      - region
      - type
      - updatedAt
    Ordering:
      description: Defines the ordering in a listing of results.
      type: string
      enum:
      - ascending
      - descending
    ListResponse_EnvironmentModelOut_:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/EnvironmentModelOut'
        iterator:
          type: string
          nullable: true
          example: iterator
        prevIterator:
          type: string
          nullable: true
          example: -iterator
        done:
          type: boolean
      required:
      - data
      - done
      - iterator
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
      description: HTTP Bearer token passed in the `Authorization` header
x-tagGroups:
- name: General
  tags:
  - Background Task
  - Environment
- name: Dispatch
  tags:
  - Application
  - Event Type
  - Authentication
  - Endpoint
  - Message
  - Message Attempt
  - Integration
  - Connector
- name: Stream
  tags:
  - Stream
  - Sink
  - Event
  - Stream Event Type
  - Stream Authentication
- name: Ingest
  tags:
  - Ingest Source
  - Ingest Endpoint
- name: Operational Webhooks
  tags:
  - Webhook
  - Webhook Endpoint
- name: Statistics
  tags:
  - Statistics
- name: Utility
  tags:
  - Health
x-webhooks:
  endpoint.created:
    post:
      tags:
      - Webhook
      summary: endpoint.created
      description: Sent when an endpoint is created.
      operationId: endpoint.created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointCreatedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.created
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.deleted:
    post:
      tags:
      - Webhook
      summary: endpoint.deleted
      description: Sent when an endpoint is deleted.
      operationId: endpoint.deleted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointDeletedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.deleted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.disabled:
    post:
      tags:
      - Webhook
      summary: endpoint.disabled
      description: Sent when an endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: endpoint.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointDisabledEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: endpoint.disabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.enabled:
    post:
      tags:
      - Webhook
      summary: endpoint.enabled
      description: Sent when an endpoint has been enabled.
      operationId: endpoint.enabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointEnabledEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.enabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.updated:
    post:
      tags:
      - Webhook
      summary: endpoint.updated
      description: Sent when an endpoint is updated.
      operationId: endpoint.updated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointUpdatedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.updated
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.exhausted:
    post:
      tags:
      - Webhook
      summary: message.attempt.exhausted
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: message.attempt.exhausted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptExhaustedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.exhausted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.failing:
    post:
      tags:
      - Webhook
      summary: message.attempt.failing
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `message.attempt.exhausted` which is sent after the last failure.'
      operationId: message.attempt.failing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptFailingEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.failing
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.recovered:
    post:
      tags:
      - Webhook
      summary: message.attempt.recovered
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: message.attempt.recovered
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptRecoveredEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.recovered
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  background_task.finished:
    post:
      tags:
      - Webhook
      summary: background_task.finished
      description: Sent when a background task is finished.
      operationId: background_task.finished
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackgroundTaskFinishedEvent'
            example:
              data:
                taskId: qtask_1srOrx2ZWZBpBUvZwXKQmoEYga2
                task: application.stats
                status: finished
                data:
                  appStats:
                  - messageDestinations: 343
                    appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                    appUid: null
              type: background_task.finished
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.endpoint.disabled:
    post:
      tags:
      - Webhook
      summary: ingest.endpoint.disabled
      description: Sent when an ingest endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: ingest.endpoint.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestEndpointDisabledEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: ingest.endpoint.disabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.exhausted:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.exhausted
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: ingest.message.attempt.exhausted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptExhaustedEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.exhausted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.failing:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.failing
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `ingest.message.attempt.exhausted` which is sent after the last failure.'
      operationId: ingest.message.attempt.failing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptFailingEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.failing
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.recovered:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.recovered
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: ingest.message.attempt.recovered
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptRecoveredEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.recovered
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  message.attempt.log:
    post:
      tags:
      - Webhook
      summary: message.attempt.log
      description: Sent after message attempts are made. Contains metadata about message attempts and their results. In order to reduce the frequency of webhooks, these are sent in batches periodically.
      operationId: message.attempt.log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptLogEvent'
            example:
              data:
              - orgId: env_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                msgCreated: '2022-11-06T15:04:05Z'
                attemptStart: '2022-11-06T15:04:06Z'
                attemptEnd: '2022-11-06T15:04:07Z'
                attemptId: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                responseStatusCode: 200
                attemptCount: 1
                status: 0
                eventType: user.signup
              type: message.attempt.log
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
      x-svix-feature-flags:
      - attempt_log
      x-internal: true
