openapi: 3.2.0
info:
  title: Svix Environment Settings API
  description: 'Welcome to the Svix API documentation!


    Useful links: [Homepage](https://www.svix.com) | [Support email](mailto:support+docs@svix.com) | [Blog](https://www.svix.com/blog/) | [Slack Community](https://www.svix.com/slack/)


    # Introduction


    This is the reference documentation and schemas for the [Svix webhook service](https://www.svix.com) API. For tutorials and other documentation please refer to [the documentation](https://docs.svix.com).


    ## Main concepts


    In Svix you have four important entities you will be interacting with:


    - `messages`: these are the webhooks being sent. They can have contents and a few other properties.

    - `application`: this is where `messages` are sent to. Usually you want to create one application for each user on your platform.

    - `endpoint`: endpoints are the URLs messages will be sent to. Each application can have multiple `endpoints` and each message sent to that application will be sent to all of them (unless they are not subscribed to the sent event type).

    - `event-type`: event types are identifiers denoting the type of the message being sent. Event types are primarily used to decide which events are sent to which endpoint.



    ## Authentication


    Get your authentication token (`AUTH_TOKEN`) from the [Svix dashboard](https://dashboard.svix.com) and use it as part of the `Authorization` header as such: `Authorization: Bearer ${AUTH_TOKEN}`. For more information on authentication, please refer to the [authentication token docs](https://docs.svix.com/api-keys).


    <SecurityDefinitions />



    ## Code samples


    The code samples assume you already have the respective libraries installed and you know how to use them. For the latest information on how to do that, please refer to [the documentation](https://docs.svix.com/).



    ## Idempotency


    Svix supports [idempotency](https://en.wikipedia.org/wiki/Idempotence) for safely retrying requests without accidentally performing the same operation twice. This is useful when an API call is disrupted in transit and you do not receive a response.


    To perform an idempotent request, pass the idempotency key in the `Idempotency-Key` header to the request. The idempotency key should be a unique value generated by the client. You can create the key in however way you like, though we suggest using UUID v4, or any other string with enough entropy to avoid collisions. Your idempotency key should not begin with the string `auto_`, which is reserved for internal use by the client libraries.


    Svix''s idempotency works by saving the resulting status code and body of the first request made for any given idempotency key for any successful request. Subsequent requests with the same key return the same result for a period of up to 12 hours.


    Please note that idempotency is only supported for `POST` requests.



    ## Cross-Origin Resource Sharing


    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    '
  version: 1.922.0
  x-logo:
    url: https://www.svix.com/static/img/brand-padded.svg
    altText: Svix Logo
servers:
- url: https://api.eu.svix.com
  description: The Svix EU region
- url: https://api.us.svix.com
  description: The Svix US region
- url: https://api.ca.svix.com
  description: The Svix Canada region
- url: https://api.au.svix.com
  description: The Svix Australia region
- url: https://api.in.svix.com
  description: The Svix India region
tags:
- name: Environment-Settings
paths:
  /api/v1/environment/settings:
    get:
      tags:
      - Environment-Settings
      summary: Get Org Settings
      description: Get the environment's settings.
      operationId: v1.environment.get-settings
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentSettingsOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
  /api/v1/management/environment-settings:
    get:
      tags:
      - Environment-Settings
      summary: Get Dashboard Organization Settings
      description: Get the environments's settings
      operationId: v1.management.environment-settings.get
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsInternalOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
    put:
      tags:
      - Environment-Settings
      summary: Update Dashboard Organization Settings
      description: Update the environment's settings
      operationId: v1.management.environment-settings.update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingsInternalIn'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsInternalUpdateOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
    patch:
      tags:
      - Environment-Settings
      summary: Patch Environment Settings
      description: Patch environment settings
      operationId: v1.management.environment-settings.patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingsInternalPatch'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsInternalOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
  /api/v1/management/environment-settings/customer-otel:
    get:
      tags:
      - Environment-Settings
      summary: Get Otel Config
      description: Get customer otel config.
      operationId: v1.management.environment-settings.get-otel-config
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtelConfigOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
    put:
      tags:
      - Environment-Settings
      summary: Update Otel Config
      description: Update customer otel config.
      operationId: v1.management.environment-settings.update-otel-config
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtelConfig'
        required: true
      responses:
        '204':
          description: no content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
    delete:
      tags:
      - Environment-Settings
      summary: Delete Otel Config
      description: Delete customer otel config.
      operationId: v1.management.environment-settings.delete-otel-config
      responses:
        '204':
          description: no content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
components:
  schemas:
    BorderRadiusConfig:
      type: object
      properties:
        button:
          $ref: '#/components/schemas/BorderRadiusEnum'
          nullable: true
        card:
          $ref: '#/components/schemas/BorderRadiusEnum'
          nullable: true
        input:
          $ref: '#/components/schemas/BorderRadiusEnum'
          nullable: true
    OtelConfig:
      type: object
      properties:
        url:
          type: string
        additionalHeaders:
          type: object
          default: null
          additionalProperties:
            type: string
          nullable: true
      required:
      - url
    SettingsInternalPatch:
      type: object
      properties:
        customColor:
          type: string
          format: color
          nullable: true
        customLogoUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        customThemeOverride:
          $ref: '#/components/schemas/CustomThemeOverride'
          nullable: true
        customStringsOverride:
          $ref: '#/components/schemas/CustomStringsOverride'
          nullable: true
        customBaseFontSize:
          type: integer
          format: int
          nullable: true
        customFontFamily:
          type: string
          nullable: true
          pattern: ^[a-zA-Z0-9\-_ ]+$
          example: Open Sans
        customFontFamilyUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        disableEndpointOnFailure:
          type: boolean
        displayName:
          type: string
          nullable: true
        enableChannels:
          type: boolean
        enableEndpointMtlsConfig:
          type: boolean
        enableEndpointOauthConfig:
          type: boolean
        enableIntegrationManagement:
          type: boolean
        enableMessageStream:
          type: boolean
        enableMsgAtmptLog:
          type: boolean
        enableOtlp:
          type: boolean
        enableTransformations:
          type: boolean
        enforceHttps:
          type: boolean
        eventCatalogPublished:
          type: boolean
        readOnly:
          type: boolean
        requireEndpointChannel:
          type: boolean
        requireEndpointFilterTypes:
          type: boolean
        retryPolicy:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        whitelabelHeaders:
          type: boolean
        sendSvixWebhookHeaders:
          type: boolean
        colorPaletteLight:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        colorPaletteDark:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        showUseSvixPlay:
          type: boolean
        wipeSuccessfulPayload:
          type: boolean
        enableApplicationAlerts:
          type: boolean
        applicationAlertEvents:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationAlertEvent'
        applicationAlertsDashboardUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        applicationAlertsLogoUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        showFeatureTooltips:
          type: boolean
        webhooksAutoConfig:
          type: boolean
        mcpToken:
          type: boolean
    ValidationError:
      description: Validation errors have their own schema to provide context for invalid requests eg. mismatched types and out of bounds values. There may be any number of these per 422 UNPROCESSABLE ENTITY error.
      type: object
      properties:
        loc:
          description: The location as a [`Vec`] of [`String`]s -- often in the form `["body", "field_name"]`, `["query", "field_name"]`, etc. They may, however, be arbitrarily deep.
          type: array
          items:
            type: string
        msg:
          description: The message accompanying the validation error item.
          type: string
        type:
          description: The type of error, often "type_error" or "value_error", but sometimes with more context like as "value_error.number.not_ge"
          type: string
      required:
      - loc
      - msg
      - type
    EnvironmentSettingsOut:
      type: object
      properties:
        customColor:
          type: string
          format: color
          nullable: true
        logoUrl:
          type: string
          format: uri
          nullable: true
        customLogoUrl:
          description: Deprecated, use `logoUrl` instead.
          type: string
          format: uri
          deprecated: true
          maxLength: 65536
          minLength: 1
          nullable: true
        customFontFamily:
          type: string
          nullable: true
          pattern: ^[a-zA-Z0-9\-_ ]+$
          example: Open Sans
        customFontFamilyUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        customThemeOverride:
          $ref: '#/components/schemas/CustomThemeOverride'
          nullable: true
        customStringsOverride:
          $ref: '#/components/schemas/CustomStringsOverride'
          nullable: true
        displayName:
          type: string
          nullable: true
        enableChannels:
          type: boolean
          default: false
        enableMessageTags:
          type: boolean
          default: false
        enableMessageStream:
          type: boolean
          default: false
        enableIntegrationManagement:
          type: boolean
          default: false
        enableTransformations:
          type: boolean
          default: false
        enableEndpointOauthConfig:
          type: boolean
          default: false
        enableEndpointMtlsConfig:
          type: boolean
          default: false
        colorPaletteLight:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        colorPaletteDark:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        showUseSvixPlay:
          type: boolean
          default: true
        showSvixBrandFooter:
          type: boolean
          default: false
        wipeSuccessfulPayload:
          type: boolean
          default: false
        showFeatureTooltips:
          type: boolean
          default: false
    FontSizeConfig:
      type: object
      properties:
        base:
          type: integer
          format: uint16
          minimum: 0
          nullable: true
    HttpErrorOut:
      title: HttpError
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
      required:
      - code
      - detail
    SettingsInternalOut:
      type: object
      properties:
        showSvixBrandFooter:
          type: boolean
          default: false
        whitelabelLogo:
          type: string
          format: uri
          default: null
          nullable: true
        retryPolicy:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        requireEndpointChannel:
          type: boolean
          default: false
        whitelabelHeaders:
          type: boolean
          default: false
        sendSvixWebhookHeaders:
          type: boolean
          default: false
        enableMsgAtmptLog:
          type: boolean
          default: false
        enableOtlp:
          type: boolean
          default: false
        customColor:
          type: string
          format: color
          nullable: true
        customLogoUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        customThemeOverride:
          $ref: '#/components/schemas/CustomThemeOverride'
          nullable: true
        customStringsOverride:
          $ref: '#/components/schemas/CustomStringsOverride'
          nullable: true
        customBaseFontSize:
          type: integer
          format: int
          nullable: true
        customFontFamily:
          type: string
          nullable: true
          pattern: ^[a-zA-Z0-9\-_ ]+$
          example: Open Sans
        customFontFamilyUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        disableEndpointOnFailure:
          type: boolean
          default: true
        displayName:
          type: string
          nullable: true
        eventCatalogPublished:
          type: boolean
          default: false
        enforceHttps:
          type: boolean
          default: true
        enableChannels:
          type: boolean
          default: false
        enableMessageStream:
          type: boolean
          default: false
        readOnly:
          type: boolean
          default: false
        enableIntegrationManagement:
          type: boolean
          default: false
        enableTransformations:
          type: boolean
          default: false
        requireEndpointFilterTypes:
          type: boolean
          default: false
        enableEndpointOauthConfig:
          type: boolean
          default: false
        enableEndpointMtlsConfig:
          type: boolean
          default: false
        colorPaletteLight:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        colorPaletteDark:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        showUseSvixPlay:
          type: boolean
          default: true
        wipeSuccessfulPayload:
          type: boolean
          default: false
        enableApplicationAlerts:
          type: boolean
          default: false
        applicationAlertEvents:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/ApplicationAlertEvent'
        applicationAlertsDashboardUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        applicationAlertsLogoUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        showFeatureTooltips:
          type: boolean
          default: false
        webhooksAutoConfig:
          type: boolean
          default: false
        mcpToken:
          type: boolean
          default: false
    SettingsInternalIn:
      type: object
      properties:
        retryPolicy:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        requireEndpointChannel:
          type: boolean
          default: false
        whitelabelHeaders:
          type: boolean
          default: false
        sendSvixWebhookHeaders:
          type: boolean
          default: false
        enableMsgAtmptLog:
          type: boolean
          default: false
        enableOtlp:
          type: boolean
          default: false
        customColor:
          type: string
          format: color
          nullable: true
        customLogoUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        customThemeOverride:
          $ref: '#/components/schemas/CustomThemeOverride'
          nullable: true
        customStringsOverride:
          $ref: '#/components/schemas/CustomStringsOverride'
          nullable: true
        customBaseFontSize:
          type: integer
          format: int
          nullable: true
        customFontFamily:
          type: string
          nullable: true
          pattern: ^[a-zA-Z0-9\-_ ]+$
          example: Open Sans
        customFontFamilyUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        disableEndpointOnFailure:
          type: boolean
          default: true
        displayName:
          type: string
          nullable: true
        eventCatalogPublished:
          type: boolean
          default: false
        enforceHttps:
          type: boolean
          default: true
        enableChannels:
          type: boolean
          default: false
        enableMessageStream:
          type: boolean
          default: false
        readOnly:
          type: boolean
          default: false
        enableIntegrationManagement:
          type: boolean
          default: false
        enableTransformations:
          type: boolean
          default: false
        requireEndpointFilterTypes:
          type: boolean
          default: false
        enableEndpointOauthConfig:
          type: boolean
          default: false
        enableEndpointMtlsConfig:
          type: boolean
          default: false
        colorPaletteLight:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        colorPaletteDark:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        showUseSvixPlay:
          type: boolean
          default: true
        wipeSuccessfulPayload:
          type: boolean
          default: false
        enableApplicationAlerts:
          type: boolean
          default: false
        applicationAlertEvents:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/ApplicationAlertEvent'
        applicationAlertsDashboardUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        applicationAlertsLogoUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        showFeatureTooltips:
          type: boolean
          default: false
        webhooksAutoConfig:
          type: boolean
          default: false
        mcpToken:
          type: boolean
          default: false
    SettingsInternalUpdateOut:
      type: object
      properties:
        retryPolicy:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        requireEndpointChannel:
          type: boolean
          default: false
        whitelabelHeaders:
          type: boolean
          default: false
        sendSvixWebhookHeaders:
          type: boolean
          default: false
        enableMsgAtmptLog:
          type: boolean
          default: false
        enableOtlp:
          type: boolean
          default: false
        customColor:
          type: string
          format: color
          nullable: true
        customLogoUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        customThemeOverride:
          $ref: '#/components/schemas/CustomThemeOverride'
          nullable: true
        customStringsOverride:
          $ref: '#/components/schemas/CustomStringsOverride'
          nullable: true
        customBaseFontSize:
          type: integer
          format: int
          nullable: true
        customFontFamily:
          type: string
          nullable: true
          pattern: ^[a-zA-Z0-9\-_ ]+$
          example: Open Sans
        customFontFamilyUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        disableEndpointOnFailure:
          type: boolean
          default: true
        displayName:
          type: string
          nullable: true
        eventCatalogPublished:
          type: boolean
          default: false
        enforceHttps:
          type: boolean
          default: true
        enableChannels:
          type: boolean
          default: false
        enableMessageStream:
          type: boolean
          default: false
        readOnly:
          type: boolean
          default: false
        enableIntegrationManagement:
          type: boolean
          default: false
        enableTransformations:
          type: boolean
          default: false
        requireEndpointFilterTypes:
          type: boolean
          default: false
        enableEndpointOauthConfig:
          type: boolean
          default: false
        enableEndpointMtlsConfig:
          type: boolean
          default: false
        colorPaletteLight:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        colorPaletteDark:
          $ref: '#/components/schemas/CustomColorPalette'
          nullable: true
        showUseSvixPlay:
          type: boolean
          default: true
        wipeSuccessfulPayload:
          type: boolean
          default: false
        enableApplicationAlerts:
          type: boolean
          default: false
        applicationAlertEvents:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/ApplicationAlertEvent'
        applicationAlertsDashboardUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        applicationAlertsLogoUrl:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          nullable: true
        showFeatureTooltips:
          type: boolean
          default: false
        webhooksAutoConfig:
          type: boolean
          default: false
        mcpToken:
          type: boolean
          default: false
    CustomThemeOverride:
      type: object
      properties:
        borderRadius:
          $ref: '#/components/schemas/BorderRadiusConfig'
          nullable: true
        fontSize:
          $ref: '#/components/schemas/FontSizeConfig'
          nullable: true
    ApplicationAlertEvent:
      type: string
      enum:
      - endpoint.disabled
      - message.attempt.exhausted
      - stream.sink.disabled
    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
      required:
      - detail
    BorderRadiusEnum:
      type: string
      enum:
      - none
      - lg
      - md
      - sm
      - full
    CustomStringsOverride:
      type: object
      properties:
        channelsOne:
          type: string
          nullable: true
        channelsMany:
          type: string
          nullable: true
        channelsHelp:
          type: string
          nullable: true
    CustomColorPalette:
      type: object
      properties:
        primary:
          type: string
          format: color
          nullable: true
        backgroundPrimary:
          type: string
          format: color
          nullable: true
        backgroundSecondary:
          type: string
          format: color
          nullable: true
        backgroundHover:
          type: string
          format: color
          nullable: true
        textPrimary:
          type: string
          format: color
          nullable: true
        textSecondary:
          type: string
          format: color
          nullable: true
        textDanger:
          type: string
          format: color
          nullable: true
        interactiveAccent:
          type: string
          format: color
          nullable: true
        navigationAccent:
          type: string
          format: color
          nullable: true
        buttonPrimary:
          type: string
          format: color
          nullable: true
        borderPrimary:
          type: string
          format: color
          nullable: true
    OtelConfigOut:
      type: object
      properties:
        url:
          type: string
          nullable: true
        additionalHeaders:
          type: object
          additionalProperties:
            type: string
          nullable: true
        svixManaged:
          type: boolean
      required:
      - svixManaged
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
      description: HTTP Bearer token passed in the `Authorization` header
x-tagGroups:
- name: General
  tags:
  - Background Task
  - Environment
- name: Dispatch
  tags:
  - Application
  - Event Type
  - Authentication
  - Endpoint
  - Message
  - Message Attempt
  - Integration
  - Connector
- name: Stream
  tags:
  - Stream
  - Sink
  - Event
  - Stream Event Type
  - Stream Authentication
- name: Ingest
  tags:
  - Ingest Source
  - Ingest Endpoint
- name: Operational Webhooks
  tags:
  - Webhook
  - Webhook Endpoint
- name: Statistics
  tags:
  - Statistics
- name: Utility
  tags:
  - Health
x-webhooks:
  endpoint.created:
    post:
      tags:
      - Webhook
      summary: endpoint.created
      description: Sent when an endpoint is created.
      operationId: endpoint.created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointCreatedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.created
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.deleted:
    post:
      tags:
      - Webhook
      summary: endpoint.deleted
      description: Sent when an endpoint is deleted.
      operationId: endpoint.deleted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointDeletedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.deleted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.disabled:
    post:
      tags:
      - Webhook
      summary: endpoint.disabled
      description: Sent when an endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: endpoint.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointDisabledEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: endpoint.disabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.enabled:
    post:
      tags:
      - Webhook
      summary: endpoint.enabled
      description: Sent when an endpoint has been enabled.
      operationId: endpoint.enabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointEnabledEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.enabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.updated:
    post:
      tags:
      - Webhook
      summary: endpoint.updated
      description: Sent when an endpoint is updated.
      operationId: endpoint.updated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointUpdatedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.updated
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.exhausted:
    post:
      tags:
      - Webhook
      summary: message.attempt.exhausted
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: message.attempt.exhausted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptExhaustedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.exhausted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.failing:
    post:
      tags:
      - Webhook
      summary: message.attempt.failing
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `message.attempt.exhausted` which is sent after the last failure.'
      operationId: message.attempt.failing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptFailingEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.failing
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.recovered:
    post:
      tags:
      - Webhook
      summary: message.attempt.recovered
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: message.attempt.recovered
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptRecoveredEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.recovered
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  background_task.finished:
    post:
      tags:
      - Webhook
      summary: background_task.finished
      description: Sent when a background task is finished.
      operationId: background_task.finished
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackgroundTaskFinishedEvent'
            example:
              data:
                taskId: qtask_1srOrx2ZWZBpBUvZwXKQmoEYga2
                task: application.stats
                status: finished
                data:
                  appStats:
                  - messageDestinations: 343
                    appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                    appUid: null
              type: background_task.finished
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.endpoint.disabled:
    post:
      tags:
      - Webhook
      summary: ingest.endpoint.disabled
      description: Sent when an ingest endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: ingest.endpoint.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestEndpointDisabledEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: ingest.endpoint.disabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.exhausted:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.exhausted
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: ingest.message.attempt.exhausted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptExhaustedEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.exhausted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.failing:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.failing
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `ingest.message.attempt.exhausted` which is sent after the last failure.'
      operationId: ingest.message.attempt.failing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptFailingEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.failing
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.recovered:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.recovered
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: ingest.message.attempt.recovered
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptRecoveredEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.recovered
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  message.attempt.log:
    post:
      tags:
      - Webhook
      summary: message.attempt.log
      description: Sent after message attempts are made. Contains metadata about message attempts and their results. In order to reduce the frequency of webhooks, these are sent in batches periodically.
      operationId: message.attempt.log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptLogEvent'
            example:
              data:
              - orgId: env_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                msgCreated: '2022-11-06T15:04:05Z'
                attemptStart: '2022-11-06T15:04:06Z'
                attemptEnd: '2022-11-06T15:04:07Z'
                attemptId: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                responseStatusCode: 200
                attemptCount: 1
                status: 0
                eventType: user.signup
              type: message.attempt.log
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
      x-svix-feature-flags:
      - attempt_log
      x-internal: true
