openapi: 3.2.0
info:
  title: Svix Statistics API
  description: 'Welcome to the Svix API documentation!


    Useful links: [Homepage](https://www.svix.com) | [Support email](mailto:support+docs@svix.com) | [Blog](https://www.svix.com/blog/) | [Slack Community](https://www.svix.com/slack/)


    # Introduction


    This is the reference documentation and schemas for the [Svix webhook service](https://www.svix.com) API. For tutorials and other documentation please refer to [the documentation](https://docs.svix.com).


    ## Main concepts


    In Svix you have four important entities you will be interacting with:


    - `messages`: these are the webhooks being sent. They can have contents and a few other properties.

    - `application`: this is where `messages` are sent to. Usually you want to create one application for each user on your platform.

    - `endpoint`: endpoints are the URLs messages will be sent to. Each application can have multiple `endpoints` and each message sent to that application will be sent to all of them (unless they are not subscribed to the sent event type).

    - `event-type`: event types are identifiers denoting the type of the message being sent. Event types are primarily used to decide which events are sent to which endpoint.



    ## Authentication


    Get your authentication token (`AUTH_TOKEN`) from the [Svix dashboard](https://dashboard.svix.com) and use it as part of the `Authorization` header as such: `Authorization: Bearer ${AUTH_TOKEN}`. For more information on authentication, please refer to the [authentication token docs](https://docs.svix.com/api-keys).


    <SecurityDefinitions />



    ## Code samples


    The code samples assume you already have the respective libraries installed and you know how to use them. For the latest information on how to do that, please refer to [the documentation](https://docs.svix.com/).



    ## Idempotency


    Svix supports [idempotency](https://en.wikipedia.org/wiki/Idempotence) for safely retrying requests without accidentally performing the same operation twice. This is useful when an API call is disrupted in transit and you do not receive a response.


    To perform an idempotent request, pass the idempotency key in the `Idempotency-Key` header to the request. The idempotency key should be a unique value generated by the client. You can create the key in however way you like, though we suggest using UUID v4, or any other string with enough entropy to avoid collisions. Your idempotency key should not begin with the string `auto_`, which is reserved for internal use by the client libraries.


    Svix''s idempotency works by saving the resulting status code and body of the first request made for any given idempotency key for any successful request. Subsequent requests with the same key return the same result for a period of up to 12 hours.


    Please note that idempotency is only supported for `POST` requests.



    ## Cross-Origin Resource Sharing


    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    '
  version: 1.922.0
  x-logo:
    url: https://www.svix.com/static/img/brand-padded.svg
    altText: Svix Logo
servers:
- url: https://api.eu.svix.com
  description: The Svix EU region
- url: https://api.us.svix.com
  description: The Svix US region
- url: https://api.ca.svix.com
  description: The Svix Canada region
- url: https://api.au.svix.com
  description: The Svix Australia region
- url: https://api.in.svix.com
  description: The Svix India region
tags:
- name: Statistics
  description: Generate statistics about your Svix utilization
paths:
  /api/v1/stats/usage/event-types:
    put:
      tags:
      - Statistics
      summary: Aggregate Event Types
      description: "Creates a background task to calculate the listed event types for all apps in the organization.\n\nNote that this endpoint is asynchronous. You will need to poll the `Get Background Task` endpoint to\nretrieve the results of the operation.\n\nThe completed background task will return a payload like the following:\n```json\n{\n  \"id\": \"qtask_33qe39Stble9Rn3ZxFrqL5ZSsjT\",\n  \"status\": \"finished\",\n  \"task\": \"event-type.aggregate\",\n  \"data\": {\n    \"event_types\": [\n      {\n        \"appId\": \"app_33W1An2Zz5cO9SWbhHsYyDmVC6m\",\n        \"explicitlySubscribedEventTypes\": [\"user.signup\", \"user.deleted\"],\n        \"hasCatchAllEndpoint\": false\n      }\n    ]\n  }\n}\n```"
      operationId: v1.statistics.aggregate-event-types
      responses:
        '202':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregateEventTypesOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-codeSamples:
      - lang: TypeScript
        label: JavaScript
        source: const response = await svix.statistics.aggregateEventTypes();
      - lang: TypeScript
        label: TypeScript
        source: const response = await svix.statistics.aggregateEventTypes();
      - lang: Python
        label: Python
        source: response = svix.statistics.aggregate_event_types()
      - lang: Python
        label: Python (Async)
        source: response = await svix.statistics.aggregate_event_types()
      - lang: Go
        label: Go
        source: response, err := svix.Statistics.AggregateEventTypes(ctx)
      - lang: Kotlin
        label: Kotlin
        source: val response = svix.statistics.aggregateEventTypes()
      - lang: Java
        label: Java
        source: var response = svix.getStatistics().aggregateEventTypes();
      - lang: Ruby
        label: Ruby
        source: response = svix.statistics.aggregate_event_types
      - lang: Rust
        label: Rust
        source: let response = svix.statistics().aggregate_event_types().await?;
      - lang: C#
        label: C#
        source: var response = svix.Statistics.AggregateEventTypes();
      - lang: PHP
        label: PHP
        source: $response = $svix->statistics->aggregateEventTypes();
      - lang: Shell
        label: CLI
        source: svix statistics aggregate-event-types
      - lang: Shell
        label: cURL
        source: "curl -X 'PUT' \\\n  'https://api.eu.svix.com/api/v1/stats/usage/event-types' \\\n  -H 'Authorization: Bearer AUTH_TOKEN' \\\n  -H 'Accept: application/json'"
  /api/v1/stats/usage/app:
    post:
      tags:
      - Statistics
      summary: Aggregate App Stats
      description: "Creates a background task to calculate the number of message attempts (`messageDestinations`) made for all applications in the environment.\n\nNote that this endpoint is asynchronous. You will need to poll the `Get Background Task` endpoint to\nretrieve the results of the operation.\n\nThe completed background task will return a payload like the following:\n```json\n{\n  \"id\": \"qtask_33qe39Stble9Rn3ZxFrqL5ZSsjT\",\n  \"status\": \"finished\",\n  \"task\": \"application.stats\",\n  \"data\": {\n    \"appStats\": [\n      {\n        \"messageDestinations\": 2,\n        \"appId\": \"app_33W1An2Zz5cO9SWbhHsYyDmVC6m\",\n        \"appUid\": null\n      }\n    ]\n  }\n}\n```"
      operationId: v1.statistics.aggregate-app-stats
      parameters:
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppUsageStatsIn'
        required: true
      responses:
        '202':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppUsageStatsOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-codeSamples:
      - lang: TypeScript
        label: JavaScript
        source: "const response = await svix.statistics.aggregateAppStats({\n  since: new Date(\"2025-10-02T20:28:42+00:00\"),\n  until: new Date(\"2025-10-02T20:28:42+00:00\"),\n  appIds: [],\n});"
      - lang: TypeScript
        label: TypeScript
        source: "const response = await svix.statistics.aggregateAppStats({\n  since: new Date(\"2025-10-02T20:28:42+00:00\"),\n  until: new Date(\"2025-10-02T20:28:42+00:00\"),\n  appIds: [],\n});"
      - lang: Python
        label: Python
        source: "response = svix.statistics.aggregate_app_stats(\n    AppUsageStatsIn(\n        since=datetime.fromisoformat(\"2025-10-02T20:28:42+00:00\"),\n        until=datetime.fromisoformat(\"2025-10-02T20:28:42+00:00\"),\n        app_ids=[],\n    ),\n)"
      - lang: Python
        label: Python (Async)
        source: "response = await svix.statistics.aggregate_app_stats(\n    AppUsageStatsIn(\n        since=datetime.fromisoformat(\"2025-10-02T20:28:42+00:00\"),\n        until=datetime.fromisoformat(\"2025-10-02T20:28:42+00:00\"),\n        app_ids=[],\n    ),\n)"
      - lang: Go
        label: Go
        source: "response, err := svix.Statistics.AggregateAppStats(\n\tctx,\n\tAppUsageStatsIn{\n\t\tSince:  time.Date(2025, 10, 2, 20, 28, 42, 0, time.UTC),\n\t\tUntil:  time.Date(2025, 10, 2, 20, 28, 42, 0, time.UTC),\n\t\tAppIds: []string{},\n\t},\n\tnil,\n)"
      - lang: Kotlin
        label: Kotlin
        source: "val response =\n    svix.statistics.aggregateAppStats(\n        AppUsageStatsIn(\n            since = Instant.parse(\"2025-10-02T20:28:42+00:00\"),\n            until = Instant.parse(\"2025-10-02T20:28:42+00:00\"),\n            appIds = setOf(),\n        )\n    )"
      - lang: Java
        label: Java
        source: "var response = svix.getStatistics()\n        .aggregateAppStats(new AppUsageStatsIn()\n            .since(OffsetDateTime.parse(\"2025-10-02T20:28:42+00:00\"))\n            .until(OffsetDateTime.parse(\"2025-10-02T20:28:42+00:00\"))\n            .appIds(Set.of()));"
      - lang: Ruby
        label: Ruby
        source: "response = svix\n  .statistics\n  .aggregate_app_stats({since: \"2025-10-02T20:28:42+00:00\", until: \"2025-10-02T20:28:42+00:00\", appIds: []})"
      - lang: Rust
        label: Rust
        source: "let response = svix\n    .statistics()\n    .aggregate_app_stats(\n        AppUsageStatsIn {\n            since: \"2025-10-02T20:28:42+00:00\".to_string(),\n            until: \"2025-10-02T20:28:42+00:00\".to_string(),\n            app_ids: Some(vec![]),\n        },\n        None,\n    )\n    .await?;"
      - lang: C#
        label: C#
        source: "var response = svix.Statistics.AggregateAppStats(\n    new AppUsageStatsIn\n    {\n        Since = DateTime.Parse(\"2025-10-02T20:28:42+00:00\"),\n        Until = DateTime.Parse(\"2025-10-02T20:28:42+00:00\"),\n        AppIds = [],\n    }\n);"
      - lang: PHP
        label: PHP
        source: "$response = $svix->statistics->aggregateAppStats(\n    AppUsageStatsIn::create(\n        since: new DateTimeImmutable(\"2025-10-02T20:28:42+00:00\"),\n        until: new DateTimeImmutable(\"2025-10-02T20:28:42+00:00\")\n    )\n    ->withAppIds([])\n);"
      - lang: Shell
        label: CLI
        source: "svix statistics aggregate-app-stats '{\n    \"since\": \"2025-10-02T20:28:42+00:00\",\n    \"until\": \"2025-10-02T20:28:42+00:00\",\n    \"appIds\": []\n  }'"
      - lang: Shell
        label: cURL
        source: "curl -X 'POST' \\\n  'https://api.eu.svix.com/api/v1/stats/usage/app' \\\n  -H 'Authorization: Bearer AUTH_TOKEN' \\\n  -H 'Accept: application/json' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"since\": \"2025-10-02T20:28:42+00:00\",\n    \"until\": \"2025-10-02T20:28:42+00:00\",\n    \"appIds\": []\n  }'"
  /api/v1/stats/endpoint/count:
    get:
      tags:
      - Statistics
      summary: Count Endpoints
      description: Count the number of active and disabled endpoints in the environment.
      operationId: v1.statistics.endpoint-count
      parameters:
      - in: query
        name: exclude_svix_play
        description: Exclude endpoints that point to a play.svix.com url from the count
        schema:
          description: Exclude endpoints that point to a play.svix.com url from the count
          type: boolean
          default: true
        style: form
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointCountOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
  /api/v1/stats/app/{app_id}/attempt:
    get:
      tags:
      - Statistics
      summary: Get App Attempt Stats
      description: Returns application-level statistics on message attempts
      operationId: v1.stats.app-attempts
      parameters:
      - in: query
        name: startDate
        description: Filter the range to data starting from this date.
        schema:
          description: Filter the range to data starting from this date.
          type: string
          format: date-time
          nullable: true
        style: form
      - in: query
        name: endDate
        description: Filter the range to data ending by this date.
        schema:
          description: Filter the range to data ending by this date.
          type: string
          format: date-time
          nullable: true
        style: form
      - in: query
        name: period
        description: The period to aggregate the data by.
        schema:
          description: The period to aggregate the data by.
          $ref: '#/components/schemas/StatisticsPeriod'
          nullable: true
        style: form
      - in: query
        name: event_types
        description: Filter response based on the event type
        schema:
          description: Filter response based on the event type
          type: array
          items:
            description: The event type's name
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
            example: user.signup
          uniqueItems: true
          nullable: true
        style: form
      - in: path
        name: app_id
        description: The Application's ID or UID.
        required: true
        schema:
          description: The Application's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttemptStatisticsResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-internal: true
components:
  schemas:
    StatisticsPeriod:
      description: Period length for a statistics data point.
      type: string
      enum:
      - OneDay
      - OneHour
      - FiveMinutes
    EndpointCountOut:
      type: object
      properties:
        active:
          type: integer
          format: uint64
          minimum: 0.0
        disabled:
          type: integer
          format: uint64
          minimum: 0.0
      required:
      - active
      - disabled
    HttpErrorOut:
      title: HttpError
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
      required:
      - code
      - detail
    BackgroundTaskStatus:
      type: string
      enum:
      - running
      - finished
      - failed
    AttemptStatisticsData:
      type: object
      properties:
        successCount:
          type: array
          items:
            type: integer
            format: int
          nullable: true
        failureCount:
          type: array
          items:
            type: integer
            format: int
          nullable: true
        canceledCount:
          type: array
          items:
            type: integer
            format: int
          nullable: true
    BackgroundTaskType:
      type: string
      enum:
      - endpoint.replay
      - endpoint.recover
      - application.stats
      - message.broadcast
      - sdk.generate
      - event-type.aggregate
      - application.purge_content
      - endpoint.bulk-replay
    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
      required:
      - detail
    ValidationError:
      description: Validation errors have their own schema to provide context for invalid requests eg. mismatched types and out of bounds values. There may be any number of these per 422 UNPROCESSABLE ENTITY error.
      type: object
      properties:
        loc:
          description: The location as a [`Vec`] of [`String`]s -- often in the form `["body", "field_name"]`, `["query", "field_name"]`, etc. They may, however, be arbitrarily deep.
          type: array
          items:
            type: string
        msg:
          description: The message accompanying the validation error item.
          type: string
        type:
          description: The type of error, often "type_error" or "value_error", but sometimes with more context like as "value_error.number.not_ge"
          type: string
      required:
      - loc
      - msg
      - type
    AttemptStatisticsResponse:
      type: object
      properties:
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        period:
          $ref: '#/components/schemas/StatisticsPeriod'
        data:
          $ref: '#/components/schemas/AttemptStatisticsData'
      required:
      - data
      - endDate
      - period
      - startDate
    AggregateEventTypesOut:
      type: object
      properties:
        id:
          description: The QueueBackgroundTask's ID.
          type: string
          maxLength: 33
          minLength: 33
          pattern: ^qtask_[A-Za-z0-9]{27}$
          example: qtask_1srOrx2ZWZBpBUvZwXKQmoEYga2
        status:
          $ref: '#/components/schemas/BackgroundTaskStatus'
        task:
          $ref: '#/components/schemas/BackgroundTaskType'
        updatedAt:
          type: string
          format: date-time
      required:
      - id
      - status
      - task
      - updatedAt
    AppUsageStatsOut:
      type: object
      properties:
        unresolvedAppIds:
          description: 'Any app IDs or UIDs received in the request that weren''t found.


            Stats will be produced for all the others.'
          type: array
          items:
            description: The Application's ID or UID.
            type: string
            maxLength: 256
            minLength: 1
            pattern: ^[a-zA-Z0-9\-_.]+$
            example: unique-identifier
          uniqueItems: true
        id:
          description: The QueueBackgroundTask's ID.
          type: string
          maxLength: 33
          minLength: 33
          pattern: ^qtask_[A-Za-z0-9]{27}$
          example: qtask_1srOrx2ZWZBpBUvZwXKQmoEYga2
        status:
          $ref: '#/components/schemas/BackgroundTaskStatus'
        task:
          $ref: '#/components/schemas/BackgroundTaskType'
        updatedAt:
          type: string
          format: date-time
      required:
      - id
      - status
      - task
      - unresolvedAppIds
      - updatedAt
    AppUsageStatsIn:
      type: object
      properties:
        since:
          type: string
          format: date-time
        until:
          type: string
          format: date-time
        appIds:
          description: 'Specific app IDs or UIDs to aggregate stats for.


            Note that if none of the given IDs or UIDs are resolved, a 422 response will be given.'
          type: array
          items:
            description: The Application's ID or UID.
            type: string
            maxLength: 256
            minLength: 1
            pattern: ^[a-zA-Z0-9\-_.]+$
            example: unique-identifier
          uniqueItems: true
          nullable: true
      required:
      - since
      - until
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
      description: HTTP Bearer token passed in the `Authorization` header
x-tagGroups:
- name: General
  tags:
  - Background Task
  - Environment
- name: Dispatch
  tags:
  - Application
  - Event Type
  - Authentication
  - Endpoint
  - Message
  - Message Attempt
  - Integration
  - Connector
- name: Stream
  tags:
  - Stream
  - Sink
  - Event
  - Stream Event Type
  - Stream Authentication
- name: Ingest
  tags:
  - Ingest Source
  - Ingest Endpoint
- name: Operational Webhooks
  tags:
  - Webhook
  - Webhook Endpoint
- name: Statistics
  tags:
  - Statistics
- name: Utility
  tags:
  - Health
x-webhooks:
  endpoint.created:
    post:
      tags:
      - Webhook
      summary: endpoint.created
      description: Sent when an endpoint is created.
      operationId: endpoint.created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointCreatedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.created
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.deleted:
    post:
      tags:
      - Webhook
      summary: endpoint.deleted
      description: Sent when an endpoint is deleted.
      operationId: endpoint.deleted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointDeletedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.deleted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.disabled:
    post:
      tags:
      - Webhook
      summary: endpoint.disabled
      description: Sent when an endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: endpoint.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointDisabledEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: endpoint.disabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.enabled:
    post:
      tags:
      - Webhook
      summary: endpoint.enabled
      description: Sent when an endpoint has been enabled.
      operationId: endpoint.enabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointEnabledEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.enabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  endpoint.updated:
    post:
      tags:
      - Webhook
      summary: endpoint.updated
      description: Sent when an endpoint is updated.
      operationId: endpoint.updated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointUpdatedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.updated
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.exhausted:
    post:
      tags:
      - Webhook
      summary: message.attempt.exhausted
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: message.attempt.exhausted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptExhaustedEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.exhausted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.failing:
    post:
      tags:
      - Webhook
      summary: message.attempt.failing
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `message.attempt.exhausted` which is sent after the last failure.'
      operationId: message.attempt.failing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptFailingEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.failing
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  message.attempt.recovered:
    post:
      tags:
      - Webhook
      summary: message.attempt.recovered
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: message.attempt.recovered
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptRecoveredEvent'
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
              type: message.attempt.recovered
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
  background_task.finished:
    post:
      tags:
      - Webhook
      summary: background_task.finished
      description: Sent when a background task is finished.
      operationId: background_task.finished
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackgroundTaskFinishedEvent'
            example:
              data:
                taskId: qtask_1srOrx2ZWZBpBUvZwXKQmoEYga2
                task: application.stats
                status: finished
                data:
                  appStats:
                  - messageDestinations: 343
                    appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                    appUid: null
              type: background_task.finished
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.endpoint.disabled:
    post:
      tags:
      - Webhook
      summary: ingest.endpoint.disabled
      description: Sent when an ingest endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: ingest.endpoint.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestEndpointDisabledEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: ingest.endpoint.disabled
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.exhausted:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.exhausted
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: ingest.message.attempt.exhausted
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptExhaustedEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.exhausted
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.failing:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.failing
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `ingest.message.attempt.exhausted` which is sent after the last failure.'
      operationId: ingest.message.attempt.failing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptFailingEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.failing
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  ingest.message.attempt.recovered:
    post:
      tags:
      - Webhook
      summary: ingest.message.attempt.recovered
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: ingest.message.attempt.recovered
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptRecoveredEvent'
            example:
              data:
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
              type: ingest.message.attempt.recovered
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
  message.attempt.log:
    post:
      tags:
      - Webhook
      summary: message.attempt.log
      description: Sent after message attempts are made. Contains metadata about message attempts and their results. In order to reduce the frequency of webhooks, these are sent in batches periodically.
      operationId: message.attempt.log
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageAttemptLogEvent'
            example:
              data:
              - orgId: env_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                msgEventId: unique-msg-identifier
                msgCreated: '2022-11-06T15:04:05Z'
                attemptStart: '2022-11-06T15:04:06Z'
                attemptEnd: '2022-11-06T15:04:07Z'
                attemptId: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                responseStatusCode: 200
                attemptCount: 1
                status: 0
                eventType: user.signup
              type: message.attempt.log
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      x-svix-group-name: dispatch
      x-svix-feature-flags:
      - attempt_log
      x-internal: true
