openapi: 3.1.0
info:
  title: Svix Application Authentication API
  description: 'Welcome to the Svix API documentation!


    Useful links: [Homepage](https://www.svix.com) | [Support email](mailto:support+docs@svix.com) | [Blog](https://www.svix.com/blog/) | [Slack Community](https://www.svix.com/slack/)


    # Introduction


    This is the reference documentation and schemas for the [Svix webhook service](https://www.svix.com) API. For tutorials and other documentation please refer to [the documentation](https://docs.svix.com).


    ## Main concepts


    In Svix you have four important entities you will be interacting with:


    - `messages`: these are the webhooks being sent. They can have contents and a few other properties.

    - `application`: this is where `messages` are sent to. Usually you want to create one application for each user on your platform.

    - `endpoint`: endpoints are the URLs messages will be sent to. Each application can have multiple `endpoints` and each message sent to that application will be sent to all of them (unless they are not subscribed to the sent event type).

    - `event-type`: event types are identifiers denoting the type of the message being sent. Event types are primarily used to decide which events are sent to which endpoint.



    ## Authentication


    Get your authentication token (`AUTH_TOKEN`) from the [Svix dashboard](https://dashboard.svix.com) and use it as part of the `Authorization` header as such: `Authorization: Bearer ${AUTH_TOKEN}`. For more information on authentication, please refer to the [authentication token docs](https://docs.svix.com/api-keys).


    <SecurityDefinitions />



    ## Code samples


    The code samples assume you already have the respective libraries installed and you know how to use them. For the latest information on how to do that, please refer to [the documentation](https://docs.svix.com/).



    ## Idempotency


    Svix supports [idempotency](https://en.wikipedia.org/wiki/Idempotence) for safely retrying requests without accidentally performing the same operation twice. This is useful when an API call is disrupted in transit and you do not receive a response.


    To perform an idempotent request, pass the idempotency key in the `Idempotency-Key` header to the request. The idempotency key should be a unique value generated by the client. You can create the key in however way you like, though we suggest using UUID v4, or any other string with enough entropy to avoid collisions. Your idempotency key should not begin with the string `auto_`, which is reserved for internal use by the client libraries.


    Svix''s idempotency works by saving the resulting status code and body of the first request made for any given idempotency key for any successful request. Subsequent requests with the same key return the same result for a period of up to 12 hours.


    Please note that idempotency is only supported for `POST` requests.



    ## Cross-Origin Resource Sharing


    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    '
  version: 1.84.0
  x-logo:
    altText: Svix Logo
    url: https://www.svix.com/static/img/brand-padded.svg
servers:
- url: https://api.eu.svix.com/
  description: The Svix EU region
- url: https://api.us.svix.com/
  description: The Svix US region
- url: https://api.ca.svix.com/
  description: The Svix Canada region
- url: https://api.au.svix.com/
  description: The Svix Australia region
- url: https://api.in.svix.com/
  description: The Svix India region
tags:
- name: Authentication
  description: Easily give your users access to our pre-built management UI.
paths:
  /api/v1/auth/app-portal-access/{app_id}:
    post:
      tags:
      - Authentication
      summary: Get Consumer App Portal Access
      description: Use this function to get magic links (and authentication codes) for connecting your users to the Consumer Application Portal.
      operationId: v1.authentication.app-portal-access
      parameters:
      - in: path
        name: app_id
        description: The Application's ID or UID.
        required: true
        schema:
          description: The Application's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppPortalAccessIn'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppPortalAccessOut'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-codeSamples:
      - label: JavaScript
        lang: TypeScript
        source: "const response = await svix.authentication.appPortalAccess(\n  \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n  {\n    application: {\n      metadata: {},\n      name: \"My first application\",\n      throttleRate: 1,\n      uid: \"unique-identifier\",\n    },\n    capabilities: [],\n    expiry: 1,\n    featureFlags: [],\n    sessionId: \"user_1FB8\",\n  }\n);"
      - label: TypeScript
        lang: TypeScript
        source: "const response = await svix.authentication.appPortalAccess(\n  \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n  {\n    application: {\n      metadata: {},\n      name: \"My first application\",\n      throttleRate: 1,\n      uid: \"unique-identifier\",\n    },\n    capabilities: [],\n    expiry: 1,\n    featureFlags: [],\n    sessionId: \"user_1FB8\",\n  }\n);"
      - label: Python
        lang: Python
        source: "response = svix.authentication.app_portal_access(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    AppPortalAccessIn(\n        application=ApplicationIn(\n            metadata={},\n            name=\"My first application\",\n            throttle_rate=1,\n            uid=\"unique-identifier\",\n        ),\n        capabilities=[],\n        expiry=1,\n        feature_flags=[],\n        session_id=\"user_1FB8\",\n    ),\n)"
      - label: Python (Async)
        lang: Python
        source: "response = await svix.authentication.app_portal_access(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    AppPortalAccessIn(\n        application=ApplicationIn(\n            metadata={},\n            name=\"My first application\",\n            throttle_rate=1,\n            uid=\"unique-identifier\",\n        ),\n        capabilities=[],\n        expiry=1,\n        feature_flags=[],\n        session_id=\"user_1FB8\",\n    ),\n)"
      - label: Go
        lang: Go
        source: "response, err := svix.Authentication.AppPortalAccess(\n\tctx,\n\t\"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n\tAppPortalAccessIn{\n\t\tApplication: new(\n\t\t\tApplicationIn{\n\t\t\t\tMetadata:     nil,\n\t\t\t\tName:         \"My first application\",\n\t\t\t\tThrottleRate: new(uint16(1)),\n\t\t\t\tUid:          new(\"unique-identifier\"),\n\t\t\t},\n\t\t),\n\t\tCapabilities: []AppPortalCapability{\"ViewBase\", \"ViewEndpointSecret\"},\n\t\tExpiry:       new(uint64(1)),\n\t\tFeatureFlags: []string{},\n\t\tSessionId:    new(\"user_1FB8\"),\n\t},\n\tnil,\n)"
      - label: Kotlin
        lang: Kotlin
        source: "val response =\n    svix.authentication.appPortalAccess(\n        \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n        AppPortalAccessIn(\n            application =\n                ApplicationIn(\n                    metadata = mapOf(),\n                    name = \"My first application\",\n                    throttleRate = 1u,\n                    uid = \"unique-identifier\",\n                ),\n            capabilities =\n                setOf(AppPortalCapability.VIEW_BASE, AppPortalCapability.VIEW_ENDPOINT_SECRET),\n            expiry = 1u,\n            featureFlags = setOf(),\n            sessionId = \"user_1FB8\",\n        ),\n    )"
      - label: Java
        lang: Java
        source: "var response = svix.getAuthentication()\n        .appPortalAccess(\n            \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n            new AppPortalAccessIn()\n                .application(new ApplicationIn()\n                    .metadata(Map.of())\n                    .name(\"My first application\")\n                    .throttleRate(1L)\n                    .uid(\"unique-identifier\"))\n                .capabilities(\n                    Set.of(AppPortalCapability.VIEW_BASE, AppPortalCapability.VIEW_ENDPOINT_SECRET))\n                .expiry(1L)\n                .featureFlags(Set.of())\n                .sessionId(\"user_1FB8\"));"
      - label: Ruby
        lang: Ruby
        source: "response = svix\n  .authentication\n  .app_portal_access(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    {\n      application: {metadata: {}, name: \"My first application\", throttleRate: 1, uid: \"unique-identifier\"},\n      capabilities: [\"ViewBase\", \"ViewEndpointSecret\"],\n      expiry: 1,\n      featureFlags: [],\n      sessionId: \"user_1FB8\"\n    }\n  )"
      - label: Rust
        lang: Rust
        source: "let response = svix\n    .authentication()\n    .app_portal_access(\n        \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\".to_string(),\n        AppPortalAccessIn {\n            application: Some(ApplicationIn {\n                metadata: Some(HashMap::new()),\n                name: \"My first application\".to_string(),\n                throttle_rate: Some(1),\n                uid: Some(\"unique-identifier\".to_string()),\n            }),\n            capabilities: Some(vec![]),\n            expiry: Some(1),\n            feature_flags: Some(vec![]),\n            session_id: Some(\"user_1FB8\".to_string()),\n        },\n        None,\n    )\n    .await?;"
      - label: C#
        lang: C#
        source: "var response = svix.Authentication.AppPortalAccess(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    new AppPortalAccessIn\n    {\n        Application = new ApplicationIn\n        {\n            Metadata = [],\n            Name = \"My first application\",\n            ThrottleRate = 1,\n            Uid = \"unique-identifier\",\n        },\n        Capabilities = [AppPortalCapability.ViewBase, AppPortalCapability.ViewEndpointSecret],\n        Expiry = 1,\n        FeatureFlags = [],\n        SessionId = \"user_1FB8\",\n    }\n);"
      - label: PHP
        lang: PHP
        source: "$response = $svix->authentication->appPortalAccess(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    AppPortalAccessIn::create()\n    ->withApplication(ApplicationIn::create(\n        name: \"My first application\"\n    )\n    ->withMetadata([])\n    ->withThrottleRate(1)\n    ->withUid(\"unique-identifier\"))\n    ->withCapabilities([])\n    ->withExpiry(1)\n    ->withFeatureFlags([])\n    ->withSessionId(\"user_1FB8\")\n);"
      - label: CLI
        lang: Shell
        source: "svix authentication app-portal-access \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\" '{\n    \"application\": {\n      \"metadata\": {},\n      \"name\": \"My first application\",\n      \"throttleRate\": 1,\n      \"uid\": \"unique-identifier\"\n    },\n    \"capabilities\": [\n      \"ViewBase\",\n      \"ViewEndpointSecret\"\n    ],\n    \"expiry\": 1,\n    \"featureFlags\": [],\n    \"sessionId\": \"user_1FB8\"\n  }'"
      - label: cURL
        lang: Shell
        source: "curl -X 'POST' \\\n  'https://api.eu.svix.com/api/v1/auth/app-portal-access/app_1srOrx2ZWZBpBUvZwXKQmoEYga2' \\\n  -H 'Authorization: Bearer AUTH_TOKEN' \\\n  -H 'Accept: application/json' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"application\": {\n      \"metadata\": {},\n      \"name\": \"My first application\",\n      \"throttleRate\": 1,\n      \"uid\": \"unique-identifier\"\n    },\n    \"capabilities\": [\n      \"ViewBase\",\n      \"ViewEndpointSecret\"\n    ],\n    \"expiry\": 1,\n    \"featureFlags\": [],\n    \"sessionId\": \"user_1FB8\"\n  }'"
  /api/v1/auth/app/{app_id}/expire-all:
    post:
      tags:
      - Authentication
      summary: Expire All
      description: Expire all of the tokens associated with a specific application.
      operationId: v1.authentication.expire-all
      parameters:
      - in: path
        name: app_id
        description: The Application's ID or UID.
        required: true
        schema:
          description: The Application's ID or UID.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
        style: simple
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationTokenExpireIn'
        required: true
      responses:
        '204':
          description: no content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-codeSamples:
      - label: JavaScript
        lang: TypeScript
        source: "await svix.authentication.expireAll(\"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\", {\n  expiry: 60,\n  sessionIds: [],\n});"
      - label: TypeScript
        lang: TypeScript
        source: "await svix.authentication.expireAll(\"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\", {\n  expiry: 60,\n  sessionIds: [],\n});"
      - label: Python
        lang: Python
        source: "svix.authentication.expire_all(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    ApplicationTokenExpireIn(\n        expiry=60,\n        session_ids=[],\n    ),\n)"
      - label: Python (Async)
        lang: Python
        source: "await svix.authentication.expire_all(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    ApplicationTokenExpireIn(\n        expiry=60,\n        session_ids=[],\n    ),\n)"
      - label: Go
        lang: Go
        source: "err := svix.Authentication.ExpireAll(\n\tctx,\n\t\"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n\tApplicationTokenExpireIn{Expiry: new(int64(60)), SessionIds: []string{}},\n\tnil,\n)"
      - label: Kotlin
        lang: Kotlin
        source: "svix.authentication.expireAll(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    ApplicationTokenExpireIn(expiry = 60, sessionIds = listOf()),\n)"
      - label: Java
        lang: Java
        source: "svix.getAuthentication()\n        .expireAll(\n            \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n            new ApplicationTokenExpireIn().expiry(60L).sessionIds(List.of()));"
      - label: Ruby
        lang: Ruby
        source: 'response = svix.authentication.expire_all("app_1srOrx2ZWZBpBUvZwXKQmoEYga2", {expiry: 60, sessionIds: []})'
      - label: Rust
        lang: Rust
        source: "svix.authentication()\n    .expire_all(\n        \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\".to_string(),\n        ApplicationTokenExpireIn {\n            expiry: Some(60),\n            session_ids: Some(vec![]),\n        },\n        None,\n    )\n    .await?;"
      - label: C#
        lang: C#
        source: "var response = svix.Authentication.ExpireAll(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    new ApplicationTokenExpireIn { Expiry = 60, SessionIds = [] }\n);"
      - label: PHP
        lang: PHP
        source: "$svix->authentication->expireAll(\n    \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\",\n    ApplicationTokenExpireIn::create()\n    ->withExpiry(60)\n    ->withSessionIds([])\n);"
      - label: CLI
        lang: Shell
        source: "svix authentication expire-all \"app_1srOrx2ZWZBpBUvZwXKQmoEYga2\" '{\n    \"expiry\": 60,\n    \"sessionIds\": []\n  }'"
      - label: cURL
        lang: Shell
        source: "curl -X 'POST' \\\n  'https://api.eu.svix.com/api/v1/auth/app/app_1srOrx2ZWZBpBUvZwXKQmoEYga2/expire-all' \\\n  -H 'Authorization: Bearer AUTH_TOKEN' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"expiry\": 60,\n    \"sessionIds\": []\n  }'"
  /api/v1/auth/logout:
    post:
      tags:
      - Authentication
      summary: Logout
      description: 'Logout an app token.


        Trying to log out other tokens will fail.'
      operationId: v1.authentication.logout
      parameters:
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      - in: header
        name: idempotency-key
        description: The request's idempotency key
        schema:
          type: string
        style: simple
      responses:
        '204':
          description: no content
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpErrorOut'
      security:
      - HTTPBearer: []
      x-codeSamples:
      - label: JavaScript
        lang: TypeScript
        source: await svix.authentication.logout();
      - label: TypeScript
        lang: TypeScript
        source: await svix.authentication.logout();
      - label: Python
        lang: Python
        source: svix.authentication.logout()
      - label: Python (Async)
        lang: Python
        source: await svix.authentication.logout()
      - label: Go
        lang: Go
        source: err := svix.Authentication.Logout(ctx, nil)
      - label: Kotlin
        lang: Kotlin
        source: "svix.authentication\n    .logout()"
      - label: Java
        lang: Java
        source: svix.getAuthentication().logout();
      - label: Ruby
        lang: Ruby
        source: response = svix.authentication.logout
      - label: Rust
        lang: Rust
        source: svix.authentication().logout(None).await?;
      - label: C#
        lang: C#
        source: var response = svix.Authentication.Logout();
      - label: PHP
        lang: PHP
        source: $svix->authentication->logout();
      - label: CLI
        lang: Shell
        source: svix authentication logout
      - label: cURL
        lang: Shell
        source: "curl -X 'POST' \\\n  'https://api.eu.svix.com/api/v1/auth/logout' \\\n  -H 'Authorization: Bearer AUTH_TOKEN'"
components:
  schemas:
    HTTPValidationError:
      type: object
      required:
      - detail
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      description: Validation errors have their own schema to provide context for invalid requests eg. mismatched types and out of bounds values. There may be any number of these per 422 UNPROCESSABLE ENTITY error.
      type: object
      required:
      - loc
      - msg
      - type
      properties:
        loc:
          description: The location as a [`Vec`] of [`String`]s -- often in the form `["body", "field_name"]`, `["query", "field_name"]`, etc. They may, however, be arbitrarily deep.
          type: array
          items:
            type: string
        msg:
          description: The message accompanying the validation error item.
          type: string
        type:
          description: The type of error, often "type_error" or "value_error", but sometimes with more context like as "value_error.number.not_ge"
          type: string
    AppPortalAccessIn:
      type: object
      properties:
        application:
          description: 'Optionally creates a new application while generating the access link.


            If the application id or uid that is used in the path already exists, this argument is ignored.'
          $ref: '#/components/schemas/ApplicationIn'
          nullable: true
        capabilities:
          description: 'Custom capabilities attached to the token, You can combine as many capabilities as necessary.


            The `ViewBase` capability is always required


            - `ViewBase`: Basic read only permissions, does not allow the user to see the endpoint secret.


            - `ViewEndpointSecret`: Allows user to view the endpoint secret.


            - `ManageEndpointSecret`: Allows user to rotate and view the endpoint secret.


            - `ManageTransformations`: Allows user to modify the endpoint transformations.


            - `CreateAttempts`: Allows user to replay missing messages and send example messages.


            - `ManageEndpoint`: Allows user to read/modify any field or configuration of an endpoint (including secrets)


            By default, the token will get all capabilities if the capabilities are not explicitly specified.'
          type: array
          items:
            $ref: '#/components/schemas/AppPortalCapability'
          uniqueItems: true
          example:
          - ViewBase
          - ViewEndpointSecret
          nullable: true
        expiry:
          description: 'How long the token will be valid for, in seconds.


            Valid values are between 1 hour and 7 days. The default is 7 days.'
          default: 604800
          type: integer
          format: uint64
          maximum: 604800.0
          minimum: 3600.0
          nullable: true
        featureFlags:
          description: The set of feature flags the created token will have access to.
          type: array
          items:
            type: string
            maxLength: 256
            pattern: ^[a-zA-Z0-9\-_.]+$
          maxItems: 25
          minItems: 1
          uniqueItems: true
          example: []
        readOnly:
          description: Whether the app portal should be in read-only mode.
          deprecated: true
          type: boolean
          nullable: true
        sessionId:
          description: 'An optional session ID to attach to the token.


            When expiring tokens with "Expire All", you can include the session ID to only expire tokens that were created with that session ID.'
          type: string
          maxLength: 64
          minLength: 1
          pattern: ^[a-zA-Z0-9@_-]+$
          example: user_1FB8
          nullable: true
    ApplicationIn:
      type: object
      required:
      - name
      properties:
        metadata:
          default: {}
          type: object
          additionalProperties:
            type: string
        name:
          description: Application name for human consumption.
          type: string
          minLength: 1
          example: My first application
        rateLimit:
          description: Deprecated, use `throttleRate` instead.
          deprecated: true
          type: integer
          format: uint16
          minimum: 1.0
          nullable: true
        throttleRate:
          description: 'Maximum messages per second to send to this application.


            Outgoing messages will be throttled to this rate.'
          type: integer
          format: uint16
          minimum: 1.0
          nullable: true
        uid:
          description: Optional unique identifier for the application.
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9\-_.]+$
          example: unique-identifier
          nullable: true
    AppPortalAccessOut:
      type: object
      required:
      - token
      - url
      properties:
        token:
          type: string
          example: appsk_kV3ts5tKPNJN4Dl25cMTfUNdmabxbX0O
        url:
          type: string
          format: uri
          maxLength: 65536
          minLength: 1
          example: https://app.svix.com/login#key=eyJhcHBJZCI6ICJhcHBfMXRSdFl
    ApplicationTokenExpireIn:
      type: object
      properties:
        expiry:
          description: How many seconds until the old key is expired.
          type: integer
          format: int64
          maximum: 259200.0
          minimum: 0.0
          example: 60
          nullable: true
        sessionIds:
          description: 'An optional list of session ids.


            If any session ids are specified, only Application tokens created with that session id will be expired.'
          type: array
          items:
            type: string
            maxLength: 64
            minLength: 1
            pattern: ^[a-zA-Z0-9@_-]+$
            example: user_1FB8
          maxItems: 1000
    AppPortalCapability:
      type: string
      enum:
      - ViewBase
      - ViewEndpointSecret
      - ManageEndpointSecret
      - ManageTransformations
      - CreateAttempts
      - ManageEndpoint
    HttpErrorOut:
      title: HttpError
      type: object
      required:
      - code
      - detail
      properties:
        code:
          type: string
        detail:
          type: string
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
      description: HTTP Bearer token passed in the `Authorization` header
x-tagGroups:
- name: General
  tags:
  - Background Task
  - Environment
- name: Dispatch
  tags:
  - Application
  - Event Type
  - Authentication
  - Endpoint
  - Message
  - Message Attempt
  - Integration
  - Connector
- name: Stream
  tags:
  - Stream
  - Sink
  - Event
  - Stream Event Type
  - Stream Authentication
- name: Ingest
  tags:
  - Ingest Source
  - Ingest Endpoint
- name: Operational Webhooks
  tags:
  - Webhook
  - Webhook Endpoint
- name: Statistics
  tags:
  - Statistics
- name: Utility
  tags:
  - Health
x-webhooks:
  background_task.finished:
    post:
      description: Sent when a background task is finished.
      operationId: background_task.finished
      requestBody:
        content:
          application/json:
            example:
              data:
                data:
                  appStats:
                  - appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                    appUid: null
                    messageDestinations: 343
                status: finished
                task: application.stats
                taskId: qtask_1srOrx2ZWZBpBUvZwXKQmoEYga2
              type: background_task.finished
            schema:
              $ref: '#/components/schemas/BackgroundTaskFinishedEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: background_task.finished
      tags:
      - Webhook
  endpoint.created:
    post:
      description: Sent when an endpoint is created.
      operationId: endpoint.created
      requestBody:
        content:
          application/json:
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.created
            schema:
              $ref: '#/components/schemas/EndpointCreatedEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: endpoint.created
      tags:
      - Webhook
      x-svix-group-name: dispatch
  endpoint.deleted:
    post:
      description: Sent when an endpoint is deleted.
      operationId: endpoint.deleted
      requestBody:
        content:
          application/json:
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.deleted
            schema:
              $ref: '#/components/schemas/EndpointDeletedEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: endpoint.deleted
      tags:
      - Webhook
      x-svix-group-name: dispatch
  endpoint.disabled:
    post:
      description: Sent when an endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: endpoint.disabled
      requestBody:
        content:
          application/json:
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                trigger: automatic
              type: endpoint.disabled
            schema:
              $ref: '#/components/schemas/EndpointDisabledEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: endpoint.disabled
      tags:
      - Webhook
      x-svix-group-name: dispatch
  endpoint.enabled:
    post:
      description: Sent when an endpoint has been enabled.
      operationId: endpoint.enabled
      requestBody:
        content:
          application/json:
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.enabled
            schema:
              $ref: '#/components/schemas/EndpointEnabledEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: endpoint.enabled
      tags:
      - Webhook
      x-svix-group-name: dispatch
  endpoint.updated:
    post:
      description: Sent when an endpoint is updated.
      operationId: endpoint.updated
      requestBody:
        content:
          application/json:
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
              type: endpoint.updated
            schema:
              $ref: '#/components/schemas/EndpointUpdatedEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: endpoint.updated
      tags:
      - Webhook
      x-svix-group-name: dispatch
  ingest.endpoint.disabled:
    post:
      description: Sent when an ingest endpoint has been automatically disabled after continuous failures, or manually via an API call.
      operationId: ingest.endpoint.disabled
      requestBody:
        content:
          application/json:
            example:
              data:
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                endpointUid: unique-endpoint-identifier
                failSince: '2022-11-06T15:04:05Z'
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
                trigger: automatic
              type: ingest.endpoint.disabled
            schema:
              $ref: '#/components/schemas/IngestEndpointDisabledEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: ingest.endpoint.disabled
      tags:
      - Webhook
  ingest.message.attempt.exhausted:
    post:
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: ingest.message.attempt.exhausted
      requestBody:
        content:
          application/json:
            example:
              data:
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
                msgEventId: unique-msg-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
              type: ingest.message.attempt.exhausted
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptExhaustedEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: ingest.message.attempt.exhausted
      tags:
      - Webhook
  ingest.message.attempt.failing:
    post:
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `ingest.message.attempt.exhausted` which is sent after the last failure.'
      operationId: ingest.message.attempt.failing
      requestBody:
        content:
          application/json:
            example:
              data:
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
                msgEventId: unique-msg-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
              type: ingest.message.attempt.failing
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptFailingEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: ingest.message.attempt.failing
      tags:
      - Webhook
  ingest.message.attempt.recovered:
    post:
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: ingest.message.attempt.recovered
      requestBody:
        content:
          application/json:
            example:
              data:
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
                msgEventId: unique-msg-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                sourceId: src_30HT9jb8WZXKVWIO44ZDr
              type: ingest.message.attempt.recovered
            schema:
              $ref: '#/components/schemas/IngestMessageAttemptRecoveredEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: ingest.message.attempt.recovered
      tags:
      - Webhook
  message.attempt.exhausted:
    post:
      description: Sent when a message delivery has failed (all of the retry attempts have been exhausted).
      operationId: message.attempt.exhausted
      requestBody:
        content:
          application/json:
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
                msgEventId: unique-msg-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
              type: message.attempt.exhausted
            schema:
              $ref: '#/components/schemas/MessageAttemptExhaustedEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: message.attempt.exhausted
      tags:
      - Webhook
      x-svix-group-name: dispatch
  message.attempt.failing:
    post:
      description: 'Sent after a message has been failing for a few times.

        It''s sent on the fourth failure. It complements `message.attempt.exhausted` which is sent after the last failure.'
      operationId: message.attempt.failing
      requestBody:
        content:
          application/json:
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 500
                  timestamp: '2022-11-06T15:04:05Z'
                msgEventId: unique-msg-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
              type: message.attempt.failing
            schema:
              $ref: '#/components/schemas/MessageAttemptFailingEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: message.attempt.failing
      tags:
      - Webhook
      x-svix-group-name: dispatch
  message.attempt.log:
    post:
      description: Sent after message attempts are made. Contains metadata about message attempts and their results. In order to reduce the frequency of webhooks, these are sent in batches periodically.
      operationId: message.attempt.log
      requestBody:
        content:
          application/json:
            example:
              data:
              - appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                attemptCount: 1
                attemptEnd: '2022-11-06T15:04:07Z'
                attemptId: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                attemptStart: '2022-11-06T15:04:06Z'
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                eventType: user.signup
                msgCreated: '2022-11-06T15:04:05Z'
                msgEventId: unique-msg-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
                orgId: env_1srOrx2ZWZBpBUvZwXKQmoEYga2
                responseStatusCode: 200
                status: 0
              type: message.attempt.log
            schema:
              $ref: '#/components/schemas/MessageAttemptLogEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: message.attempt.log
      tags:
      - Webhook
      x-internal: true
      x-svix-feature-flags:
      - attempt_log
      x-svix-group-name: dispatch
  message.attempt.recovered:
    post:
      description: Sent on a successful dispatch after an earlier failure op webhook has already been sent.
      operationId: message.attempt.recovered
      requestBody:
        content:
          application/json:
            example:
              data:
                appId: app_1srOrx2ZWZBpBUvZwXKQmoEYga2
                appUid: unique-app-identifier
                endpointId: ep_1srOrx2ZWZBpBUvZwXKQmoEYga2
                lastAttempt:
                  id: atmpt_1srOrx2ZWZBpBUvZwXKQmoEYga2
                  responseStatusCode: 200
                  timestamp: '2022-11-06T15:04:05Z'
                msgEventId: unique-msg-identifier
                msgId: msg_1srOrx2ZWZBpBUvZwXKQmoEYga2
              type: message.attempt.recovered
            schema:
              $ref: '#/components/schemas/MessageAttemptRecoveredEvent'
      responses:
        2XX:
          description: Return any 2XX status to indicate that the data was received successfully
      summary: message.attempt.recovered
      tags:
      - Webhook
      x-svix-group-name: dispatch
